//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.FIS {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LesInLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LesInLog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FIS.LesInLog", typeof(LesInLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ASNNo 的本地化字符串。
        /// </summary>
        public static string LesINLog_ASNNo {
            get {
                return ResourceManager.GetString("LesINLog_ASNNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ErrorCause 的本地化字符串。
        /// </summary>
        public static string LesINLog_ErrorCause {
            get {
                return ResourceManager.GetString("LesINLog_ErrorCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExtNo 的本地化字符串。
        /// </summary>
        public static string LesINLog_ExtNo {
            get {
                return ResourceManager.GetString("LesINLog_ExtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileName 的本地化字符串。
        /// </summary>
        public static string LesINLog_FileName {
            get {
                return ResourceManager.GetString("LesINLog_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HandResult 的本地化字符串。
        /// </summary>
        public static string LesINLog_HandResult {
            get {
                return ResourceManager.GetString("LesINLog_HandResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HandTime 的本地化字符串。
        /// </summary>
        public static string LesINLog_HandTime {
            get {
                return ResourceManager.GetString("LesINLog_HandTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsCreateDat 的本地化字符串。
        /// </summary>
        public static string LesINLog_IsCreateDat {
            get {
                return ResourceManager.GetString("LesINLog_IsCreateDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string LesINLog_Item {
            get {
                return ResourceManager.GetString("LesINLog_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string LesINLog_ItemDescription {
            get {
                return ResourceManager.GetString("LesINLog_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocTo 的本地化字符串。
        /// </summary>
        public static string LesINLog_LocTo {
            get {
                return ResourceManager.GetString("LesINLog_LocTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MoveType 的本地化字符串。
        /// </summary>
        public static string LesINLog_MoveType {
            get {
                return ResourceManager.GetString("LesINLog_MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PO 的本地化字符串。
        /// </summary>
        public static string LesINLog_PO {
            get {
                return ResourceManager.GetString("LesINLog_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POLine 的本地化字符串。
        /// </summary>
        public static string LesINLog_POLine {
            get {
                return ResourceManager.GetString("LesINLog_POLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceiptStatus 的本地化字符串。
        /// </summary>
        public static string LesINLog_ReceiptStatus {
            get {
                return ResourceManager.GetString("LesINLog_ReceiptStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceivedQty 的本地化字符串。
        /// </summary>
        public static string LesINLog_ReceivedQty {
            get {
                return ResourceManager.GetString("LesINLog_ReceivedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferenceCode 的本地化字符串。
        /// </summary>
        public static string LesINLog_ReferenceCode {
            get {
                return ResourceManager.GetString("LesINLog_ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipQty 的本地化字符串。
        /// </summary>
        public static string LesINLog_ShipQty {
            get {
                return ResourceManager.GetString("LesINLog_ShipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string LesINLog_Type {
            get {
                return ResourceManager.GetString("LesINLog_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WmsNo 的本地化字符串。
        /// </summary>
        public static string LesINLog_WMSNo {
            get {
                return ResourceManager.GetString("LesINLog_WMSNo", resourceCulture);
            }
        }
    }
}
