//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.FIS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WMSDatFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WMSDatFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FIS.WMSDatFile", typeof(WMSDatFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelQty.
        /// </summary>
        public static string WMSDatFile_CancelQty {
            get {
                return ResourceManager.GetString("WMSDatFile_CancelQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string WMSDatFile_CreateDate {
            get {
                return ResourceManager.GetString("WMSDatFile_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentReceiveQty.
        /// </summary>
        public static string WMSDatFile_CurrentReceiveQty {
            get {
                return ResourceManager.GetString("WMSDatFile_CurrentReceiveQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessage.
        /// </summary>
        public static string WMSDatFile_ErrorMessage {
            get {
                return ResourceManager.GetString("WMSDatFile_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsHand.
        /// </summary>
        public static string WMSDatFile_IsHand {
            get {
                return ResourceManager.GetString("WMSDatFile_IsHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string WMSDatFile_Item {
            get {
                return ResourceManager.GetString("WMSDatFile_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string WMSDatFile_ItemDescription {
            get {
                return ResourceManager.GetString("WMSDatFile_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGORT.
        /// </summary>
        public static string WMSDatFile_LGORT {
            get {
                return ResourceManager.GetString("WMSDatFile_LGORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveType.
        /// </summary>
        public static string WMSDatFile_MoveType {
            get {
                return ResourceManager.GetString("WMSDatFile_MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderQty.
        /// </summary>
        public static string WMSDatFile_OrderQty {
            get {
                return ResourceManager.GetString("WMSDatFile_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string WMSDatFile_Qty {
            get {
                return ResourceManager.GetString("WMSDatFile_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedQty.
        /// </summary>
        public static string WMSDatFile_ReceivedQty {
            get {
                return ResourceManager.GetString("WMSDatFile_ReceivedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveLotSize.
        /// </summary>
        public static string WMSDatFile_ReceiveLotSize {
            get {
                return ResourceManager.GetString("WMSDatFile_ReceiveLotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveTotal.
        /// </summary>
        public static string WMSDatFile_ReceiveTotal {
            get {
                return ResourceManager.GetString("WMSDatFile_ReceiveTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LesReceipt.
        /// </summary>
        public static string WMSDatFile_RecNo {
            get {
                return ResourceManager.GetString("WMSDatFile_RecNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string WMSDatFile_ReferenceItemCode {
            get {
                return ResourceManager.GetString("WMSDatFile_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequirementDate.
        /// </summary>
        public static string WMSDatFile_RequirementDate {
            get {
                return ResourceManager.GetString("WMSDatFile_RequirementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string WMSDatFile_Result {
            get {
                return ResourceManager.GetString("WMSDatFile_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMLGO.
        /// </summary>
        public static string WMSDatFile_UMLGO {
            get {
                return ResourceManager.GetString("WMSDatFile_UMLGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string WMSDatFile_Uom {
            get {
                return ResourceManager.GetString("WMSDatFile_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMSId.
        /// </summary>
        public static string WMSDatFile_WMSId {
            get {
                return ResourceManager.GetString("WMSDatFile_WMSId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WmsNo.
        /// </summary>
        public static string WMSDatFile_WmsNo {
            get {
                return ResourceManager.GetString("WMSDatFile_WmsNo", resourceCulture);
            }
        }
    }
}
