//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SCM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickStrategy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickStrategy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SCM.PickStrategy", typeof(PickStrategy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string PickStrategy_Code {
            get {
                return ResourceManager.GetString("PickStrategy_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDevan.
        /// </summary>
        public static string PickStrategy_IsDevan {
            get {
                return ResourceManager.GetString("PickStrategy_IsDevan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFulfillUC.
        /// </summary>
        public static string PickStrategy_IsFulfillUC {
            get {
                return ResourceManager.GetString("PickStrategy_IsFulfillUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOddOccupy.
        /// </summary>
        public static string PickStrategy_IsOddOccupy {
            get {
                return ResourceManager.GetString("PickStrategy_IsOddOccupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPickFromBin.
        /// </summary>
        public static string PickStrategy_IsPickFromBin {
            get {
                return ResourceManager.GetString("PickStrategy_IsPickFromBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OddOption.
        /// </summary>
        public static string PickStrategy_OddOption {
            get {
                return ResourceManager.GetString("PickStrategy_OddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipStrategy.
        /// </summary>
        public static string PickStrategy_ShipStrategy {
            get {
                return ResourceManager.GetString("PickStrategy_ShipStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickStrategy has been updated successfully..
        /// </summary>
        public static string PickStrategy_Updated {
            get {
                return ResourceManager.GetString("PickStrategy_Updated", resourceCulture);
            }
        }
    }
}
