//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CUST {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VehicleInFactoryMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleInFactoryMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CUST.VehicleInFactoryMaster", typeof(VehicleInFactoryMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDate.
        /// </summary>
        public static string VehicleInFactory_CloseDate {
            get {
                return ResourceManager.GetString("VehicleInFactory_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseUserName.
        /// </summary>
        public static string VehicleInFactory_CloseUserName {
            get {
                return ResourceManager.GetString("VehicleInFactory_CloseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleInFactory Created.
        /// </summary>
        public static string VehicleInFactory_Created {
            get {
                return ResourceManager.GetString("VehicleInFactory_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string VehicleInFactory_CreateDate {
            get {
                return ResourceManager.GetString("VehicleInFactory_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string VehicleInFactory_CreateUserName {
            get {
                return ResourceManager.GetString("VehicleInFactory_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateFrom.
        /// </summary>
        public static string VehicleInFactory_DateFrom {
            get {
                return ResourceManager.GetString("VehicleInFactory_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTo.
        /// </summary>
        public static string VehicleInFactory_DateTo {
            get {
                return ResourceManager.GetString("VehicleInFactory_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpNo Is Empty.
        /// </summary>
        public static string VehicleInFactory_IpNoIsEmpty {
            get {
                return ResourceManager.GetString("VehicleInFactory_IpNoIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInFactory.
        /// </summary>
        public static string VehicleInFactory_IsInFactory {
            get {
                return ResourceManager.GetString("VehicleInFactory_IsInFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string VehicleInFactory_LastModifyDate {
            get {
                return ResourceManager.GetString("VehicleInFactory_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string VehicleInFactory_LastModifyUserName {
            get {
                return ResourceManager.GetString("VehicleInFactory_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string VehicleInFactory_OrderNo {
            get {
                return ResourceManager.GetString("VehicleInFactory_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string VehicleInFactory_Plant {
            get {
                return ResourceManager.GetString("VehicleInFactory_Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string VehicleInFactory_Status {
            get {
                return ResourceManager.GetString("VehicleInFactory_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleNo.
        /// </summary>
        public static string VehicleInFactory_VehicleNo {
            get {
                return ResourceManager.GetString("VehicleInFactory_VehicleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string VehicleInFactoryMaster_Audit {
            get {
                return ResourceManager.GetString("VehicleInFactoryMaster_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseInfo.
        /// </summary>
        public static string VehicleInFactoryMaster_BaseInfo {
            get {
                return ResourceManager.GetString("VehicleInFactoryMaster_BaseInfo", resourceCulture);
            }
        }
    }
}
