//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.KB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KanbanScan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KanbanScan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.KB.KanbanScan", typeof(KanbanScan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsTempKanbanCard.
        /// </summary>
        public static string IsTempKanbanCard {
            get {
                return ResourceManager.GetString("IsTempKanbanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string KanbanScan_CardNo {
            get {
                return ResourceManager.GetString("KanbanScan_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string KanbanScan_Container {
            get {
                return ResourceManager.GetString("KanbanScan_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanban scan has been deleted successfully..
        /// </summary>
        public static string KanbanScan_Deleted {
            get {
                return ResourceManager.GetString("KanbanScan_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit kanban scan.
        /// </summary>
        public static string KanbanScan_Edit_Title {
            get {
                return ResourceManager.GetString("KanbanScan_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete kanban scan..
        /// </summary>
        public static string KanbanScan_FailedDelete {
            get {
                return ResourceManager.GetString("KanbanScan_FailedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string KanbanScan_Flow {
            get {
                return ResourceManager.GetString("KanbanScan_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string KanbanScan_Item {
            get {
                return ResourceManager.GetString("KanbanScan_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item description.
        /// </summary>
        public static string KanbanScan_ItemDescription {
            get {
                return ResourceManager.GetString("KanbanScan_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location bin.
        /// </summary>
        public static string KanbanScan_LocBin {
            get {
                return ResourceManager.GetString("KanbanScan_LocBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic center code.
        /// </summary>
        public static string KanbanScan_LogisticCenterCode {
            get {
                return ResourceManager.GetString("KanbanScan_LogisticCenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No..
        /// </summary>
        public static string KanbanScan_OrderNo {
            get {
                return ResourceManager.GetString("KanbanScan_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order qty.
        /// </summary>
        public static string KanbanScan_OrderQty {
            get {
                return ResourceManager.GetString("KanbanScan_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order time.
        /// </summary>
        public static string KanbanScan_OrderTime {
            get {
                return ResourceManager.GetString("KanbanScan_OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order user name.
        /// </summary>
        public static string KanbanScan_OrderUserName {
            get {
                return ResourceManager.GetString("KanbanScan_OrderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLineNo.
        /// </summary>
        public static string KanbanScan_POLineNo {
            get {
                return ResourceManager.GetString("KanbanScan_POLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO No.
        /// </summary>
        public static string KanbanScan_PONo {
            get {
                return ResourceManager.GetString("KanbanScan_PONo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qi tiao bian.
        /// </summary>
        public static string KanbanScan_QiTiaoBian {
            get {
                return ResourceManager.GetString("KanbanScan_QiTiaoBian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string KanbanScan_Qty {
            get {
                return ResourceManager.GetString("KanbanScan_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string KanbanScan_Region {
            get {
                return ResourceManager.GetString("KanbanScan_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name.
        /// </summary>
        public static string KanbanScan_RegionName {
            get {
                return ResourceManager.GetString("KanbanScan_RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan qty.
        /// </summary>
        public static string KanbanScan_ScanQty {
            get {
                return ResourceManager.GetString("KanbanScan_ScanQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan time.
        /// </summary>
        public static string KanbanScan_ScanTime {
            get {
                return ResourceManager.GetString("KanbanScan_ScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan user name.
        /// </summary>
        public static string KanbanScan_ScanUserName {
            get {
                return ResourceManager.GetString("KanbanScan_ScanUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        public static string KanbanScan_Sequence {
            get {
                return ResourceManager.GetString("KanbanScan_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        public static string KanbanScan_Shelf {
            get {
                return ResourceManager.GetString("KanbanScan_Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string KanbanScan_Supplier {
            get {
                return ResourceManager.GetString("KanbanScan_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier name.
        /// </summary>
        public static string KanbanScan_SupplierName {
            get {
                return ResourceManager.GetString("KanbanScan_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempKanbanCard.
        /// </summary>
        public static string KanbanScan_TempKanbanCard {
            get {
                return ResourceManager.GetString("KanbanScan_TempKanbanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string KanbanScan_Uom {
            get {
                return ResourceManager.GetString("KanbanScan_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanban scan has been updated successfully..
        /// </summary>
        public static string KanbanScan_Updated {
            get {
                return ResourceManager.GetString("KanbanScan_Updated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kanban scan has been updated successfully..
        /// </summary>
        public static string KanbanScan_ReferenceItemCode
        {
            get
            {
                return ResourceManager.GetString("KanbanScan_ReferenceItemCode", resourceCulture);
            }
        }
    }
}
