//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Mangt..
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control.
        /// </summary>
        public static string Application_Access_Control {
            get {
                return ResourceManager.GetString("Application_Access_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Mangt..
        /// </summary>
        public static string Application_Address {
            get {
                return ResourceManager.GetString("Application_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bom.
        /// </summary>
        public static string Application_Bom {
            get {
                return ResourceManager.GetString("Application_Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string Application_Container {
            get {
                return ResourceManager.GetString("Application_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency mangt..
        /// </summary>
        public static string Application_Currency {
            get {
                return ResourceManager.GetString("Application_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityPreference.
        /// </summary>
        public static string Application_EntityPreference {
            get {
                return ResourceManager.GetString("Application_EntityPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinanceCalendar.
        /// </summary>
        public static string Application_FinanceCalendar {
            get {
                return ResourceManager.GetString("Application_FinanceCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Calendar .
        /// </summary>
        public static string Application_FinanceCalendar_Close {
            get {
                return ResourceManager.GetString("Application_FinanceCalendar_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item mangt..
        /// </summary>
        public static string Application_Item {
            get {
                return ResourceManager.GetString("Application_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCategory mangt..
        /// </summary>
        public static string Application_ItemCategory {
            get {
                return ResourceManager.GetString("Application_ItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDiscontinue.
        /// </summary>
        public static string Application_ItemDiscontinue {
            get {
                return ResourceManager.GetString("Application_ItemDiscontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Mangt..
        /// </summary>
        public static string Application_Location {
            get {
                return ResourceManager.GetString("Application_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission  Mangt.
        /// </summary>
        public static string Application_Permission {
            get {
                return ResourceManager.GetString("Application_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionGroup   mangt.
        /// </summary>
        public static string Application_PermissionGroup {
            get {
                return ResourceManager.GetString("Application_PermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Application_Region {
            get {
                return ResourceManager.GetString("Application_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Mangt..
        /// </summary>
        public static string Application_Role {
            get {
                return ResourceManager.GetString("Application_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Mangt..
        /// </summary>
        public static string Application_Routing {
            get {
                return ResourceManager.GetString("Application_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTake.
        /// </summary>
        public static string Application_StockTake {
            get {
                return ResourceManager.GetString("Application_StockTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom Mangt..
        /// </summary>
        public static string Application_Uom {
            get {
                return ResourceManager.GetString("Application_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mangt..
        /// </summary>
        public static string Application_User {
            get {
                return ResourceManager.GetString("Application_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userfavorite mangt..
        /// </summary>
        public static string Application_UserFav {
            get {
                return ResourceManager.GetString("Application_UserFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkingCalendar mangt..
        /// </summary>
        public static string Application_WorkingCalendar {
            get {
                return ResourceManager.GetString("Application_WorkingCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleLineItem.
        /// </summary>
        public static string Cust_ScheduleLineItem {
            get {
                return ResourceManager.GetString("Cust_ScheduleLineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASNGap.
        /// </summary>
        public static string Distribution_ASNGap {
            get {
                return ResourceManager.GetString("Distribution_ASNGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View ASNGap.
        /// </summary>
        public static string Distribution_ASNGap_View {
            get {
                return ResourceManager.GetString("Distribution_ASNGap_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Flow.
        /// </summary>
        public static string Distribution_DistributionFlow {
            get {
                return ResourceManager.GetString("Distribution_DistributionFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpGap.
        /// </summary>
        public static string Distribution_IpGap {
            get {
                return ResourceManager.GetString("Distribution_IpGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        public static string Distribution_IpGap_Adjust {
            get {
                return ResourceManager.GetString("Distribution_IpGap_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Distribution_IpGap_View {
            get {
                return ResourceManager.GetString("Distribution_IpGap_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpMaster.
        /// </summary>
        public static string Distribution_IpMaster {
            get {
                return ResourceManager.GetString("Distribution_IpMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Distribution_IpMaster_Receive {
            get {
                return ResourceManager.GetString("Distribution_IpMaster_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Distribution_IpMaster_View {
            get {
                return ResourceManager.GetString("Distribution_IpMaster_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Order.
        /// </summary>
        public static string Distribution_OrderMstr {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Process.
        /// </summary>
        public static string Distribution_OrderMstr_BatchProcess {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Distribution_OrderMstr_New {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickNew.
        /// </summary>
        public static string Distribution_OrderMstr_QuickNew {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_QuickNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Distribution_OrderMstr_Return {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Distribution_OrderMstr_ReturnIndex {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_ReturnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Distribution_OrderMstr_ReturnNew {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_ReturnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string Distribution_OrderMstr_Ship {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Distribution_OrderMstr_View {
            get {
                return ResourceManager.GetString("Distribution_OrderMstr_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickList.
        /// </summary>
        public static string Distribution_PickList {
            get {
                return ResourceManager.GetString("Distribution_PickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Distribution_PickList_New {
            get {
                return ResourceManager.GetString("Distribution_PickList_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string Distribution_PickList_Ship {
            get {
                return ResourceManager.GetString("Distribution_PickList_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Distribution_PickList_View {
            get {
                return ResourceManager.GetString("Distribution_PickList_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution PriceList.
        /// </summary>
        public static string Distribution_PriceList {
            get {
                return ResourceManager.GetString("Distribution_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Distribution_Receipt {
            get {
                return ResourceManager.GetString("Distribution_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Distribution_Receipt_View {
            get {
                return ResourceManager.GetString("Distribution_Receipt_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnReceipt.
        /// </summary>
        public static string DIstribution_ReturnReceipt {
            get {
                return ResourceManager.GetString("DIstribution_ReturnReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string DIstribution_ReturnReceipt_View {
            get {
                return ResourceManager.GetString("DIstribution_ReturnReceipt_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceOrder.
        /// </summary>
        public static string Distribution_SequenceOrder {
            get {
                return ResourceManager.GetString("Distribution_SequenceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Distribution_Setup_Customer {
            get {
                return ResourceManager.GetString("Distribution_Setup_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTire.
        /// </summary>
        public static string DIstribution_ShipTire {
            get {
                return ResourceManager.GetString("DIstribution_ShipTire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string DistributionShipTire_View {
            get {
                return ResourceManager.GetString("DistributionShipTire_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuLocationLotDetail.
        /// </summary>
        public static string HuLocationLotDetail_Inventorys {
            get {
                return ResourceManager.GetString("HuLocationLotDetail.Inventorys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string InspectionOrder_Detail {
            get {
                return ResourceManager.GetString("InspectionOrder_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge.
        /// </summary>
        public static string InspectionOrder_Judge {
            get {
                return ResourceManager.GetString("InspectionOrder_Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectResultExt.
        /// </summary>
        public static string InspectResultExt_View {
            get {
                return ResourceManager.GetString("InspectResultExt_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu.
        /// </summary>
        public static string Inventory_Hu {
            get {
                return ResourceManager.GetString("Inventory_Hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Inventory_Hu_New {
            get {
                return ResourceManager.GetString("Inventory_Hu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Inventory_Hu_View {
            get {
                return ResourceManager.GetString("Inventory_Hu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InMiscOrder.
        /// </summary>
        public static string Inventory_InMiscOrder {
            get {
                return ResourceManager.GetString("Inventory_InMiscOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Inventory_InMiscOrder_New {
            get {
                return ResourceManager.GetString("Inventory_InMiscOrder_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Inventory_InMiscOrder_View {
            get {
                return ResourceManager.GetString("Inventory_InMiscOrder_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryFreeze.
        /// </summary>
        public static string Inventory_InventoryFreeze {
            get {
                return ResourceManager.GetString("Inventory_InventoryFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Inventory_InventoryFreeze_View {
            get {
                return ResourceManager.GetString("Inventory_InventoryFreeze_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemExchange.
        /// </summary>
        public static string Inventory_ItemExchange {
            get {
                return ResourceManager.GetString("Inventory_ItemExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Inventory_ItemExchange_View {
            get {
                return ResourceManager.GetString("Inventory_ItemExchange_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KanBanCard.
        /// </summary>
        public static string Inventory_KanBanCard_View {
            get {
                return ResourceManager.GetString("Inventory_KanBanCard_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutMiscOrder.
        /// </summary>
        public static string Inventory_OutMiscOrder {
            get {
                return ResourceManager.GetString("Inventory_OutMiscOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Inventory_OutMiscOrder_New {
            get {
                return ResourceManager.GetString("Inventory_OutMiscOrder_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Inventory_OutMiscOrder_View {
            get {
                return ResourceManager.GetString("Inventory_OutMiscOrder_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTake.
        /// </summary>
        public static string Inventory_StockTake {
            get {
                return ResourceManager.GetString("Inventory_StockTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Inventory_StockTake_New {
            get {
                return ResourceManager.GetString("Inventory_StockTake_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Inventory_StockTake_View {
            get {
                return ResourceManager.GetString("Inventory_StockTake_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Flow.
        /// </summary>
        public static string Inventory_TransferFlow {
            get {
                return ResourceManager.GetString("Inventory_TransferFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcurementInfo.
        /// </summary>
        public static string Menu_ProcurementInfo {
            get {
                return ResourceManager.GetString("Menu.ProcurementInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nondelivery.
        /// </summary>
        public static string Nondelivery_Procurement_View {
            get {
                return ResourceManager.GetString("Nondelivery_Procurement_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution_Receipt.
        /// </summary>
        public static string OrderMstr_Distribution_Receipt {
            get {
                return ResourceManager.GetString("OrderMstr_Distribution_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickStrategy.
        /// </summary>
        public static string PickStrategy {
            get {
                return ResourceManager.GetString("PickStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProdLineLocationDet.
        /// </summary>
        public static string PRD_ProdLineLocationDet {
            get {
                return ResourceManager.GetString("PRD_ProdLineLocationDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding.
        /// </summary>
        public static string PRD_ProdLineLocationDetFeed {
            get {
                return ResourceManager.GetString("PRD_ProdLineLocationDetFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Process.
        /// </summary>
        public static string Procduction_OrderMstr_BatchProcess {
            get {
                return ResourceManager.GetString("Procduction_OrderMstr_BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerGoods Flow.
        /// </summary>
        public static string Procurement_CustomerGoodsFlow {
            get {
                return ResourceManager.GetString("Procurement_CustomerGoodsFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpGap.
        /// </summary>
        public static string Procurement_IpGap {
            get {
                return ResourceManager.GetString("Procurement_IpGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        public static string Procurement_IpGap_Adjust {
            get {
                return ResourceManager.GetString("Procurement_IpGap_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Procurement_IpGap_View {
            get {
                return ResourceManager.GetString("Procurement_IpGap_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpMaster.
        /// </summary>
        public static string Procurement_IpMaster {
            get {
                return ResourceManager.GetString("Procurement_IpMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Procurement_IpMaster_Cancel {
            get {
                return ResourceManager.GetString("Procurement_IpMaster_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Procurement_IpMaster_Receive {
            get {
                return ResourceManager.GetString("Procurement_IpMaster_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Procurement_IpMaster_View {
            get {
                return ResourceManager.GetString("Procurement_IpMaster_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement OrderMstr.
        /// </summary>
        public static string Procurement_OrderMstr {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Process.
        /// </summary>
        public static string Procurement_OrderMstr_BatchProcess {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Procurement_OrderMstr_New {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickNew.
        /// </summary>
        public static string Procurement_OrderMstr_QuickNew {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_QuickNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Procurement_OrderMstr_Receive {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Procurement_OrderMstr_Return {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Procurement_OrderMstr_ReturnIndex {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_ReturnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Procurement_OrderMstr_ReturnNew {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_ReturnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Procurement_OrderMstr_View {
            get {
                return ResourceManager.GetString("Procurement_OrderMstr_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement PriceList.
        /// </summary>
        public static string Procurement_PriceList {
            get {
                return ResourceManager.GetString("Procurement_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Flow.
        /// </summary>
        public static string Procurement_ProcurementFlow {
            get {
                return ResourceManager.GetString("Procurement_ProcurementFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Procurement_Receipt {
            get {
                return ResourceManager.GetString("Procurement_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Procurement_Receipt_View {
            get {
                return ResourceManager.GetString("Procurement_Receipt_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Order.
        /// </summary>
        public static string Procurement_SequenceOrder {
            get {
                return ResourceManager.GetString("Procurement_SequenceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Procurement_SequenceOrder_View {
            get {
                return ResourceManager.GetString("Procurement_SequenceOrder_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQOrderMstr.
        /// </summary>
        public static string Procurement_SQOrderMstr {
            get {
                return ResourceManager.GetString("Procurement_SQOrderMstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQOrderMstr_Cancel.
        /// </summary>
        public static string Procurement_SQOrderMstr_Cancel {
            get {
                return ResourceManager.GetString("Procurement_SQOrderMstr_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Procurement_SQOrderMstr_View {
            get {
                return ResourceManager.GetString("Procurement_SQOrderMstr_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subconctracting Flow.
        /// </summary>
        public static string Procurement_SubconctractingFlow {
            get {
                return ResourceManager.GetString("Procurement_SubconctractingFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleInFactory.
        /// </summary>
        public static string Procurement_VehicleInFactory {
            get {
                return ResourceManager.GetString("Procurement_VehicleInFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Procurement_VehicleInFactory_New {
            get {
                return ResourceManager.GetString("Procurement_VehicleInFactory_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Procurement_VehicleInFactory_View {
            get {
                return ResourceManager.GetString("Procurement_VehicleInFactory_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialIn.
        /// </summary>
        public static string Production_MaterialIn {
            get {
                return ResourceManager.GetString("Production_MaterialIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackFlush.
        /// </summary>
        public static string Production_MaterialIn_BackFlush {
            get {
                return ResourceManager.GetString("Production_MaterialIn_BackFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed OrderMaster.
        /// </summary>
        public static string Production_MaterialIn_FeedOrderMaster {
            get {
                return ResourceManager.GetString("Production_MaterialIn_FeedOrderMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed ProductLine.
        /// </summary>
        public static string Production_MaterialIn_FeedProductLine {
            get {
                return ResourceManager.GetString("Production_MaterialIn_FeedProductLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Feed OrderMaster.
        /// </summary>
        public static string Production_MaterialIn_ForceFeedOrderMaster {
            get {
                return ResourceManager.GetString("Production_MaterialIn_ForceFeedOrderMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Feed ProductLine.
        /// </summary>
        public static string Production_MaterialIn_ForceFeedProductLine {
            get {
                return ResourceManager.GetString("Production_MaterialIn_ForceFeedProductLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnProductLine.
        /// </summary>
        public static string Production_MaterialIn_ReturnProductLine {
            get {
                return ResourceManager.GetString("Production_MaterialIn_ReturnProductLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnReturnOrderMaster.
        /// </summary>
        public static string Production_MaterialIn_ReturnReturnOrderMaster {
            get {
                return ResourceManager.GetString("Production_MaterialIn_ReturnReturnOrderMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Production_MaterialIn_View {
            get {
                return ResourceManager.GetString("Production_MaterialIn_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster Pause.
        /// </summary>
        public static string Production_OrderMaster_Pause {
            get {
                return ResourceManager.GetString("Production_OrderMaster_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Production_OrderMaster_Resume {
            get {
                return ResourceManager.GetString("Production_OrderMaster_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Order.
        /// </summary>
        public static string Production_OrderMstr {
            get {
                return ResourceManager.GetString("Production_OrderMstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Process.
        /// </summary>
        public static string Production_OrderMstr_BatchProcess {
            get {
                return ResourceManager.GetString("Production_OrderMstr_BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FZComplete.
        /// </summary>
        public static string Production_OrderMstr_FZComplete {
            get {
                return ResourceManager.GetString("Production_OrderMstr_FZComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Production_OrderMstr_Import {
            get {
                return ResourceManager.GetString("Production_OrderMstr_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Production_OrderMstr_New {
            get {
                return ResourceManager.GetString("Production_OrderMstr_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick New.
        /// </summary>
        public static string Production_OrderMstr_QuickNew {
            get {
                return ResourceManager.GetString("Production_OrderMstr_QuickNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Production_OrderMstr_Receive {
            get {
                return ResourceManager.GetString("Production_OrderMstr_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Production_OrderMstr_View {
            get {
                return ResourceManager.GetString("Production_OrderMstr_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Flow.
        /// </summary>
        public static string Production_ProductionFlow {
            get {
                return ResourceManager.GetString("Production_ProductionFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLine Pause.
        /// </summary>
        public static string Production_ProductLine_Pause {
            get {
                return ResourceManager.GetString("Production_ProductLine_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeqImport.
        /// </summary>
        public static string Production_SeqImport {
            get {
                return ResourceManager.GetString("Production_SeqImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConcessionOrder.
        /// </summary>
        public static string Quality_ConcessionOrder {
            get {
                return ResourceManager.GetString("Quality_ConcessionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Quality_ConcessionOrder_New {
            get {
                return ResourceManager.GetString("Quality_ConcessionOrder_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Quality_ConcessionOrder_View {
            get {
                return ResourceManager.GetString("Quality_ConcessionOrder_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Order.
        /// </summary>
        public static string Quality_InspectionOrder {
            get {
                return ResourceManager.GetString("Quality_InspectionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectionOrder Transfer.
        /// </summary>
        public static string Quality_InspectionOrder_Transfer {
            get {
                return ResourceManager.GetString("Quality_InspectionOrder_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RejectOrder.
        /// </summary>
        public static string Quality_RejectOrder {
            get {
                return ResourceManager.GetString("Quality_RejectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Quality_RejectOrder_Detail {
            get {
                return ResourceManager.GetString("Quality_RejectOrder_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New RejectOrder.
        /// </summary>
        public static string Quality_RejectOrder_New {
            get {
                return ResourceManager.GetString("Quality_RejectOrder_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Quality_RejectOrder_Return {
            get {
                return ResourceManager.GetString("Quality_RejectOrder_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RejectOrder Transfer.
        /// </summary>
        public static string Quality_RejectOrder_Transfer {
            get {
                return ResourceManager.GetString("Quality_RejectOrder_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View RejectOrder.
        /// </summary>
        public static string Quality_RejectOrder_View {
            get {
                return ResourceManager.GetString("Quality_RejectOrder_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkersWaste.
        /// </summary>
        public static string Quality_RejectOrder_WorkersWaste {
            get {
                return ResourceManager.GetString("Quality_RejectOrder_WorkersWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string QualityDoor_New {
            get {
                return ResourceManager.GetString("QualityDoor_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string QualityDoor_View {
            get {
                return ResourceManager.GetString("QualityDoor_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleLine.
        /// </summary>
        public static string ScheduleLine_OrderMstr_View {
            get {
                return ResourceManager.GetString("ScheduleLine_OrderMstr_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleLine.
        /// </summary>
        public static string ScheduleLine_View {
            get {
                return ResourceManager.GetString("ScheduleLine_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string SequenceOrder_Detail {
            get {
                return ResourceManager.GetString("SequenceOrder_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SequenceOrder_View {
            get {
                return ResourceManager.GetString("SequenceOrder_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0085Supplier.
        /// </summary>
        public static string Supplier_SupplierPortal {
            get {
                return ResourceManager.GetString("Supplier_SupplierPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Bill.
        /// </summary>
        public static string SupplierActBill {
            get {
                return ResourceManager.GetString("SupplierActBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string SupplierBill {
            get {
                return ResourceManager.GetString("SupplierBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASN.
        /// </summary>
        public static string SupplierIpMaster {
            get {
                return ResourceManager.GetString("SupplierIpMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string SupplierOrder {
            get {
                return ResourceManager.GetString("SupplierOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string SupplierOrderIssue {
            get {
                return ResourceManager.GetString("SupplierOrderIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Bill.
        /// </summary>
        public static string SupplierPlanBill {
            get {
                return ResourceManager.GetString("SupplierPlanBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Hu.
        /// </summary>
        public static string SupplierPrintHu {
            get {
                return ResourceManager.GetString("SupplierPrintHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string SupplierReceipt {
            get {
                return ResourceManager.GetString("SupplierReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string SupplierSchedule {
            get {
                return ResourceManager.GetString("SupplierSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian.
        /// </summary>
        public static string Url_Custodian {
            get {
                return ResourceManager.GetString("Url_Custodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Url_Customer_View {
            get {
                return ResourceManager.GetString("Url_Customer_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeferredFeedCounter.
        /// </summary>
        public static string Url_DeferredFeedCounter_View {
            get {
                return ResourceManager.GetString("Url_DeferredFeedCounter_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Inspection Order.
        /// </summary>
        public static string Url_InspectionOrder_New {
            get {
                return ResourceManager.GetString("Url_InspectionOrder_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Inspection Order.
        /// </summary>
        public static string Url_InspectionOrder_View {
            get {
                return ResourceManager.GetString("Url_InspectionOrder_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShelfLifeWarning.
        /// </summary>
        public static string URL_Inventory_ShelfLifeWarning {
            get {
                return ResourceManager.GetString("URL_Inventory_ShelfLifeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueLevel.
        /// </summary>
        public static string Url_IssueLevel_View {
            get {
                return ResourceManager.GetString("Url_IssueLevel_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueType.
        /// </summary>
        public static string Url_IssueType_View {
            get {
                return ResourceManager.GetString("Url_IssueType_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KanBanCard.
        /// </summary>
        public static string Url_KanBanCardInfo_View {
            get {
                return ResourceManager.GetString("Url_KanBanCardInfo_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要货单导入.
        /// </summary>
        public static string Url_OrderMstr_Procurement_Import {
            get {
                return ResourceManager.GetString("Url_OrderMstr_Procurement_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityDoor.
        /// </summary>
        public static string Url_QualityDoor {
            get {
                return ResourceManager.GetString("Url_QualityDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Url_SCM_Flow_Purchase_View {
            get {
                return ResourceManager.GetString("Url_SCM_Flow_Purchase_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Url_Supplier_View {
            get {
                return ResourceManager.GetString("Url_Supplier_View", resourceCulture);
            }
        }
    }
}
