//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.PRD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiSupplySupplier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiSupplySupplier() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PRD.MultiSupplySupplier", typeof(MultiSupplySupplier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MultiSupplySupplier has been added successfully. 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Added {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CycleQty 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_CycleQty {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_CycleQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MultiSupplySupplier has been deleted successfully. 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Deleted {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit MultiSupplySupplier 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Edit_Title {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This supplier ({0}) already exists. Please try a different supplier. 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Existing_Supplier {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Existing_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GroupNo 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_GroupNo {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_GroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsActive 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_IsActive {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New MultiSupplySupplier 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_New_Title {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proportion 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Proportion {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Proportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seq 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Seq {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpillQty 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_SpillQty {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_SpillQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Supplier {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MultiSupplySupplier has been updated successfully. 的本地化字符串。
        /// </summary>
        public static string MultiSupplySupplier_Updated {
            get {
                return ResourceManager.GetString("MultiSupplySupplier_Updated", resourceCulture);
            }
        }
    }
}
