//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.PRD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShiftMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftMaster() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PRD.ShiftMaster", typeof(ShiftMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ShiftMaster has been added successfully. 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Added {
            get {
                return ResourceManager.GetString("ShiftMaster_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Code {
            get {
                return ResourceManager.GetString("ShiftMaster_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShiftMaster has been deleted successfully. 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Deleted {
            get {
                return ResourceManager.GetString("ShiftMaster_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Detail {
            get {
                return ResourceManager.GetString("ShiftMaster_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit ShiftMaster 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Edit_Title {
            get {
                return ResourceManager.GetString("ShiftMaster_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line {0}:{1}Can not be Empty. 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_LineFieldCanNotBeNull {
            get {
                return ResourceManager.GetString("ShiftMaster_LineFieldCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Name {
            get {
                return ResourceManager.GetString("ShiftMaster_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New ShiftMaster 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_New_Title {
            get {
                return ResourceManager.GetString("ShiftMaster_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} line: route the vendor delivery period of reference to the frequency of breakdown, please re-confirm the save number. 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_NotDeletedShiftMaster {
            get {
                return ResourceManager.GetString("ShiftMaster_NotDeletedShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line {0}: route vendor delivery period refers to the frequency of detail can not be modified. 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_NotUpdatedShiftMaster {
            get {
                return ResourceManager.GetString("ShiftMaster_NotUpdatedShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save ShiftMaster 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Save {
            get {
                return ResourceManager.GetString("ShiftMaster_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Shift {
            get {
                return ResourceManager.GetString("ShiftMaster_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShiftMaster has been updated successfully. 的本地化字符串。
        /// </summary>
        public static string ShiftMaster_Updated {
            get {
                return ResourceManager.GetString("ShiftMaster_Updated", resourceCulture);
            }
        }
    }
}
