//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.PRD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkingCalendar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkingCalendar() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PRD.WorkingCalendar", typeof(WorkingCalendar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 If the corresponding date there is no consistent standardcalendar,will as a rest. 的本地化字符串。
        /// </summary>
        public static string ConfirmNewWorkingCalendar {
            get {
                return ResourceManager.GetString("ConfirmNewWorkingCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkingCalendar has been added successfully. 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Added {
            get {
                return ResourceManager.GetString("WorkingCalendar_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Category 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Category {
            get {
                return ResourceManager.GetString("WorkingCalendar_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DayOfWeek 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_DayOfWeek {
            get {
                return ResourceManager.GetString("WorkingCalendar_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DayOfWeekDescription 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_DayOfWeekDescription {
            get {
                return ResourceManager.GetString("WorkingCalendar_DayOfWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkingCalendar has been deleted successfully. 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Deleted {
            get {
                return ResourceManager.GetString("WorkingCalendar_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit WorkingCalendar 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Edit_Title {
            get {
                return ResourceManager.GetString("WorkingCalendar_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_EndDate {
            get {
                return ResourceManager.GetString("WorkingCalendar_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate Can Not Less Than Now. 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_EndDateCanNotLessThanNow {
            get {
                return ResourceManager.GetString("WorkingCalendar_EndDateCanNotLessThanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate Must Greater Than StartDate 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_EndDateMustGreaterThanStartDate {
            get {
                return ResourceManager.GetString("WorkingCalendar_EndDateMustGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndWorkingDate 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_EndWorkingDate {
            get {
                return ResourceManager.GetString("WorkingCalendar_EndWorkingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowStrategy 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_FlowStrategy {
            get {
                return ResourceManager.GetString("WorkingCalendar_FlowStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add  WorkingCalendar 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_New_Title {
            get {
                return ResourceManager.GetString("WorkingCalendar_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProdLine 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_ProdLine {
            get {
                return ResourceManager.GetString("WorkingCalendar_ProdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Region {
            get {
                return ResourceManager.GetString("WorkingCalendar_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegionName 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_RegionName {
            get {
                return ResourceManager.GetString("WorkingCalendar_RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Shift {
            get {
                return ResourceManager.GetString("WorkingCalendar_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartWorkingDate 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_StartWorkingDate {
            get {
                return ResourceManager.GetString("WorkingCalendar_StartWorkingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Type {
            get {
                return ResourceManager.GetString("WorkingCalendar_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkingCalendar has been updated successfully. 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_Updated {
            get {
                return ResourceManager.GetString("WorkingCalendar_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkingDate 的本地化字符串。
        /// </summary>
        public static string WorkingCalendar_WorkingDate {
            get {
                return ResourceManager.GetString("WorkingCalendar_WorkingDate", resourceCulture);
            }
        }
    }
}
