//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Hu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hu() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.Hu", typeof(Hu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CreateDate 的本地化字符串。
        /// </summary>
        public static string Hu_CreateDate {
            get {
                return ResourceManager.GetString("Hu_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateUserName 的本地化字符串。
        /// </summary>
        public static string Hu_CreateUserName {
            get {
                return ResourceManager.GetString("Hu_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate 的本地化字符串。
        /// </summary>
        public static string Hu_EndDate {
            get {
                return ResourceManager.GetString("Hu_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FirstInventoryDate 的本地化字符串。
        /// </summary>
        public static string Hu_FirstInventoryDate {
            get {
                return ResourceManager.GetString("Hu_FirstInventoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string Hu_Flow {
            get {
                return ResourceManager.GetString("Hu_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowDetail 的本地化字符串。
        /// </summary>
        public static string Hu_FlowDetail {
            get {
                return ResourceManager.GetString("Hu_FlowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu Created 的本地化字符串。
        /// </summary>
        public static string Hu_HuCreatedByFlow {
            get {
                return ResourceManager.GetString("Hu_HuCreatedByFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu Created 的本地化字符串。
        /// </summary>
        public static string Hu_HuCreatedByOrder {
            get {
                return ResourceManager.GetString("Hu_HuCreatedByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuId 的本地化字符串。
        /// </summary>
        public static string Hu_HuId {
            get {
                return ResourceManager.GetString("Hu_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuPrintedByIpMaster 的本地化字符串。
        /// </summary>
        public static string Hu_HuPrintedByIpMaster {
            get {
                return ResourceManager.GetString("Hu_HuPrintedByIpMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuStatusDescription 的本地化字符串。
        /// </summary>
        public static string Hu_HuStatusDescription {
            get {
                return ResourceManager.GetString("Hu_HuStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpDetail 的本地化字符串。
        /// </summary>
        public static string Hu_IpDetail {
            get {
                return ResourceManager.GetString("Hu_IpDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsOdd 的本地化字符串。
        /// </summary>
        public static string Hu_IsOdd {
            get {
                return ResourceManager.GetString("Hu_IsOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string Hu_Item {
            get {
                return ResourceManager.GetString("Hu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string Hu_ItemDescription {
            get {
                return ResourceManager.GetString("Hu_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationTo 的本地化字符串。
        /// </summary>
        public static string Hu_LocationTo {
            get {
                return ResourceManager.GetString("Hu_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lotNo 的本地化字符串。
        /// </summary>
        public static string Hu_lotNo {
            get {
                return ResourceManager.GetString("Hu_lotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 manufacture date 的本地化字符串。
        /// </summary>
        public static string Hu_manufacture_date {
            get {
                return ResourceManager.GetString("Hu_manufacture_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManufactureParty 的本地化字符串。
        /// </summary>
        public static string Hu_ManufactureParty {
            get {
                return ResourceManager.GetString("Hu_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderDetail 的本地化字符串。
        /// </summary>
        public static string Hu_OrderDetail {
            get {
                return ResourceManager.GetString("Hu_OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderNo 的本地化字符串。
        /// </summary>
        public static string Hu_OrderNo {
            get {
                return ResourceManager.GetString("Hu_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 print 的本地化字符串。
        /// </summary>
        public static string Hu_Printde {
            get {
                return ResourceManager.GetString("Hu_Printde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty 的本地化字符串。
        /// </summary>
        public static string Hu_Qty {
            get {
                return ResourceManager.GetString("Hu_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferenceItemCode 的本地化字符串。
        /// </summary>
        public static string Hu_ReferenceItemCode {
            get {
                return ResourceManager.GetString("Hu_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemindExpireDate 的本地化字符串。
        /// </summary>
        public static string Hu_RemindExpireDate {
            get {
                return ResourceManager.GetString("Hu_RemindExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemindExpireDate_End 的本地化字符串。
        /// </summary>
        public static string Hu_RemindExpireDate_End {
            get {
                return ResourceManager.GetString("Hu_RemindExpireDate_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemindExpireDate_start 的本地化字符串。
        /// </summary>
        public static string Hu_RemindExpireDate_start {
            get {
                return ResourceManager.GetString("Hu_RemindExpireDate_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartDate 的本地化字符串。
        /// </summary>
        public static string Hu_StartDate {
            get {
                return ResourceManager.GetString("Hu_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SupplierLotNo 的本地化字符串。
        /// </summary>
        public static string Hu_SupplierLotNo {
            get {
                return ResourceManager.GetString("Hu_SupplierLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowMaster 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_FlowMaster {
            get {
                return ResourceManager.GetString("Hu_Tab_FlowMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_Hu {
            get {
                return ResourceManager.GetString("Hu_Tab_Hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPMaster 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_IPMaster {
            get {
                return ResourceManager.GetString("Hu_Tab_IPMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_Item {
            get {
                return ResourceManager.GetString("Hu_Tab_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderMaster 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_OrderMaster {
            get {
                return ResourceManager.GetString("Hu_Tab_OrderMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码打印成功,共打印了{0}张条码 的本地化字符串。
        /// </summary>
        public static string Hu_Template_Point {
            get {
                return ResourceManager.GetString("Hu_Template_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitCount 的本地化字符串。
        /// </summary>
        public static string Hu_UnitCount {
            get {
                return ResourceManager.GetString("Hu_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string Hu_Uom {
            get {
                return ResourceManager.GetString("Hu_Uom", resourceCulture);
            }
        }
    }
}
