//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemExchange {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemExchange() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.ItemExchange", typeof(ItemExchange).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string ItemExchange_Added {
            get {
                return ResourceManager.GetString("ItemExchange_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string ItemExchange_Canceled {
            get {
                return ResourceManager.GetString("ItemExchange_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string ItemExchange_CreateDate {
            get {
                return ResourceManager.GetString("ItemExchange_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string ItemExchange_CreateUserName {
            get {
                return ResourceManager.GetString("ItemExchange_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDate.
        /// </summary>
        public static string ItemExchange_EffectiveDate {
            get {
                return ResourceManager.GetString("ItemExchange_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemFrom.
        /// </summary>
        public static string ItemExchange_ItemFrom {
            get {
                return ResourceManager.GetString("ItemExchange_ItemFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemTo.
        /// </summary>
        public static string ItemExchange_ItemTo {
            get {
                return ResourceManager.GetString("ItemExchange_ItemTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string ItemExchange_LocationFrom {
            get {
                return ResourceManager.GetString("ItemExchange_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string ItemExchange_LocationTo {
            get {
                return ResourceManager.GetString("ItemExchange_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ItemExchange_New_Title {
            get {
                return ResourceManager.GetString("ItemExchange_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string ItemExchange_Qty {
            get {
                return ResourceManager.GetString("ItemExchange_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityType.
        /// </summary>
        public static string ItemExchange_QualityType {
            get {
                return ResourceManager.GetString("ItemExchange_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionFrom.
        /// </summary>
        public static string ItemExchange_RegionFrom {
            get {
                return ResourceManager.GetString("ItemExchange_RegionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionTo.
        /// </summary>
        public static string ItemExchange_RegionTo {
            get {
                return ResourceManager.GetString("ItemExchange_RegionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string ItemExchange_Uom {
            get {
                return ResourceManager.GetString("ItemExchange_Uom", resourceCulture);
            }
        }
    }
}
