//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockTakeLocation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockTakeLocation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.StockTakeLocation", typeof(StockTakeLocation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTakeLocation has been added successfully..
        /// </summary>
        public static string StockTakeLocation_Added {
            get {
                return ResourceManager.GetString("StockTakeLocation_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTakeLocation has been deleted successfully..
        /// </summary>
        public static string StockTakeLocation_Deleted {
            get {
                return ResourceManager.GetString("StockTakeLocation_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        public static string StockTakeLocation_Location {
            get {
                return ResourceManager.GetString("StockTakeLocation_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string StockTakeLocation_LocationName {
            get {
                return ResourceManager.GetString("StockTakeLocation_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTakeLocation has been Updated successfully..
        /// </summary>
        public static string StockTakeLocation_Updated {
            get {
                return ResourceManager.GetString("StockTakeLocation_Updated", resourceCulture);
            }
        }
    }
}
