//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockTakeResultSummary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockTakeResultSummary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.StockTakeResultSummary", typeof(StockTakeResultSummary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab_Title.
        /// </summary>
        public static string StockTakeResult_Tab_Title {
            get {
                return ResourceManager.GetString("StockTakeResult_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string StockTakeResultSummary_Bin {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakEvenCount.
        /// </summary>
        public static string StockTakeResultSummary_BreakEvenCount {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_BreakEvenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail_Title.
        /// </summary>
        public static string StockTakeResultSummary_Detail_Title {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DifferenceQty.
        /// </summary>
        public static string StockTakeResultSummary_DifferenceQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_DifferenceQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuId.
        /// </summary>
        public static string StockTakeResultSummary_HuId {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string StockTakeResultSummary_Id {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryQty.
        /// </summary>
        public static string StockTakeResultSummary_InventoryQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_InventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string StockTakeResultSummary_Item {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string StockTakeResultSummary_ItemDescription {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string StockTakeResultSummary_Location {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string StockTakeResultSummary_LotNo {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchQty.
        /// </summary>
        public static string StockTakeResultSummary_MatchQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_MatchQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfitQty.
        /// </summary>
        public static string StockTakeResultSummary_ProfitQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_ProfitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string StockTakeResultSummary_Qty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortageQty.
        /// </summary>
        public static string StockTakeResultSummary_ShortageQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_ShortageQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StNo.
        /// </summary>
        public static string StockTakeResultSummary_StNo {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_StNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTakeQty.
        /// </summary>
        public static string StockTakeResultSummary_StockTakeQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_StockTakeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string StockTakeResultSummary_Uom {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Uom", resourceCulture);
            }
        }
    }
}
