IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USP_BAK_TrunTable]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USP_BAK_TrunTable]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_BAK_TrunTable]
AS
BEGIN
	----run at 7:00AM
	TRUNCATE TABLE SAP_Item
	TRUNCATE TABLE SAP_Quota
	TRUNCATE TABLE SAP_Supplier
	TRUNCATE TABLE SAP_ProdOrder
	TRUNCATE TABLE SAP_ProdRoutingDet
	TRUNCATE TABLE SAP_ProdBomDet
END 
GO
