//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Item {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Item() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.Item", typeof(Item).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not maintain uom convertion of material {0} between {1} and {2}..
        /// </summary>
        public static string Errors_Item_UomConvertionNotFound {
            get {
                return ResourceManager.GetString("Errors_Item_UomConvertionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitting {0} not maintain any children..
        /// </summary>
        public static string Errors_ItemKit_ChildrenItemNotFound {
            get {
                return ResourceManager.GetString("Errors_ItemKit_ChildrenItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been added successfully..
        /// </summary>
        public static string Item_Added {
            get {
                return ResourceManager.GetString("Item_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BESKZ.
        /// </summary>
        public static string Item_BESKZ {
            get {
                return ResourceManager.GetString("Item_BESKZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bom.
        /// </summary>
        public static string Item_Bom {
            get {
                return ResourceManager.GetString("Item_Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Item_Code {
            get {
                return ResourceManager.GetString("Item_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string Item_Container {
            get {
                return ResourceManager.GetString("Item_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainerDesc.
        /// </summary>
        public static string Item_ContainerDesc {
            get {
                return ResourceManager.GetString("Item_ContainerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Day.
        /// </summary>
        public static string Item_Day {
            get {
                return ResourceManager.GetString("Item_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been deleted successfully..
        /// </summary>
        public static string Item_Deleted {
            get {
                return ResourceManager.GetString("Item_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Item_Description {
            get {
                return ResourceManager.GetString("Item_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPO.
        /// </summary>
        public static string Item_DISPO {
            get {
                return ResourceManager.GetString("Item_DISPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        public static string Item_Edit_Title {
            get {
                return ResourceManager.GetString("Item_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTWG.
        /// </summary>
        public static string Item_EXTWG {
            get {
                return ResourceManager.GetString("Item_EXTWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu Qty.
        /// </summary>
        public static string Item_HuQty {
            get {
                return ResourceManager.GetString("Item_HuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuUnitCount.
        /// </summary>
        public static string Item_HuUnitCount {
            get {
                return ResourceManager.GetString("Item_HuUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuUom.
        /// </summary>
        public static string Item_HuUom {
            get {
                return ResourceManager.GetString("Item_HuUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string Item_IsActive {
            get {
                return ResourceManager.GetString("Item_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCustomerGoods.
        /// </summary>
        public static string Item_IsCustomerGoods {
            get {
                return ResourceManager.GetString("Item_IsCustomerGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Freeze.
        /// </summary>
        public static string Item_IsInvFreeze {
            get {
                return ResourceManager.GetString("Item_IsInvFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsKit.
        /// </summary>
        public static string Item_IsKit {
            get {
                return ResourceManager.GetString("Item_IsKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsManufacture.
        /// </summary>
        public static string Item_IsManufacture {
            get {
                return ResourceManager.GetString("Item_IsManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPurchase.
        /// </summary>
        public static string Item_IsPurchase {
            get {
                return ResourceManager.GetString("Item_IsPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSales.
        /// </summary>
        public static string Item_IsSales {
            get {
                return ResourceManager.GetString("Item_IsSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subContract.
        /// </summary>
        public static string Item_IsSubContract {
            get {
                return ResourceManager.GetString("Item_IsSubContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsVirtual.
        /// </summary>
        public static string Item_IsVirtual {
            get {
                return ResourceManager.GetString("Item_IsVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCategory.
        /// </summary>
        public static string Item_ItemCategory {
            get {
                return ResourceManager.GetString("Item_ItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Item_Location {
            get {
                return ResourceManager.GetString("Item_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string Item_LotNo {
            get {
                return ResourceManager.GetString("Item_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string Item_ManufactureParty {
            get {
                return ResourceManager.GetString("Item_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinUnitCount.
        /// </summary>
        public static string Item_MinUnitCount {
            get {
                return ResourceManager.GetString("Item_MinUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string Item_New_Title {
            get {
                return ResourceManager.GetString("Item_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotBackFlush.
        /// </summary>
        public static string Item_NotBackFlush {
            get {
                return ResourceManager.GetString("Item_NotBackFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLIFZ.
        /// </summary>
        public static string Item_PLIFZ {
            get {
                return ResourceManager.GetString("Item_PLIFZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceCode.
        /// </summary>
        public static string Item_ReferenceCode {
            get {
                return ResourceManager.GetString("Item_ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing.
        /// </summary>
        public static string Item_Routing {
            get {
                return ResourceManager.GetString("Item_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortCode.
        /// </summary>
        public static string Item_ShortCode {
            get {
                return ResourceManager.GetString("Item_ShortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOBSL.
        /// </summary>
        public static string Item_SOBSL {
            get {
                return ResourceManager.GetString("Item_SOBSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Model.
        /// </summary>
        public static string Item_SpecifiedModel {
            get {
                return ResourceManager.GetString("Item_SpecifiedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplierLotNo.
        /// </summary>
        public static string Item_supplierLotNo {
            get {
                return ResourceManager.GetString("Item_supplierLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item_Tab_Title {
            get {
                return ResourceManager.GetString("Item_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UC.
        /// </summary>
        public static string Item_UC {
            get {
                return ResourceManager.GetString("Item_UC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string Item_Uom {
            get {
                return ResourceManager.GetString("Item_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been updated successfully..
        /// </summary>
        public static string Item_Updated {
            get {
                return ResourceManager.GetString("Item_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn Lead Time.
        /// </summary>
        public static string Item_WarnLeadTime {
            get {
                return ResourceManager.GetString("Item_WarnLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty.
        /// </summary>
        public static string Item_Warranty {
            get {
                return ResourceManager.GetString("Item_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code has been existed..
        /// </summary>
        public static string ItemErrors_Existing_Code {
            get {
                return ResourceManager.GetString("ItemErrors_Existing_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the bom code is not exist..
        /// </summary>
        public static string ItemErrors_NotExisting_Bom {
            get {
                return ResourceManager.GetString("ItemErrors_NotExisting_Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the location code is not exist..
        /// </summary>
        public static string ItemErrors_NotExisting_Location {
            get {
                return ResourceManager.GetString("ItemErrors_NotExisting_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the routing code is not exist..
        /// </summary>
        public static string ItemErrors_NotExisting_Routing {
            get {
                return ResourceManager.GetString("ItemErrors_NotExisting_Routing", resourceCulture);
            }
        }
    }
}
