//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationBin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationBin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.LocationBin", typeof(LocationBin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationBin has been Added successfully..
        /// </summary>
        public static string LocationBin_Added {
            get {
                return ResourceManager.GetString("LocationBin_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string LocationBin_Code {
            get {
                return ResourceManager.GetString("LocationBin_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationBin has been Deleted successfully..
        /// </summary>
        public static string LocationBin_Deleted {
            get {
                return ResourceManager.GetString("LocationBin_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit LocationBin.
        /// </summary>
        public static string LocationBin_Edit_Title {
            get {
                return ResourceManager.GetString("LocationBin_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string LocationBin_IsActive {
            get {
                return ResourceManager.GetString("LocationBin_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LocationBin_Name {
            get {
                return ResourceManager.GetString("LocationBin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New LocationBin.
        /// </summary>
        public static string LocationBin_New_Title {
            get {
                return ResourceManager.GetString("LocationBin_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationBin.
        /// </summary>
        public static string LocationBin_Tab_Title {
            get {
                return ResourceManager.GetString("LocationBin_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationBin has been updated successfully..
        /// </summary>
        public static string LocationBin_Updated {
            get {
                return ResourceManager.GetString("LocationBin_Updated", resourceCulture);
            }
        }
    }
}
