//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Party {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Party() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.Party", typeof(Party).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Party has been Added  successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Added {
            get {
                return ResourceManager.GetString("Party_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address Code 的本地化字符串。
        /// </summary>
        public static string Party_AddressCode {
            get {
                return ResourceManager.GetString("Party_AddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Party_AddressName {
            get {
                return ResourceManager.GetString("Party_AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string Party_Code {
            get {
                return ResourceManager.GetString("Party_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Party 的本地化字符串。
        /// </summary>
        public static string Party_CurrentParty {
            get {
                return ResourceManager.GetString("Party_CurrentParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer has been added successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Added {
            get {
                return ResourceManager.GetString("Party_Customer_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Code 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Code {
            get {
                return ResourceManager.GetString("Party_Customer_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer has been Deleted successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Deleted {
            get {
                return ResourceManager.GetString("Party_Customer_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Customer 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Edit_Title {
            get {
                return ResourceManager.GetString("Party_Customer_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer  has  been  Existing 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Errors_Existing_Code {
            get {
                return ResourceManager.GetString("Party_Customer_Errors_Existing_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name  has  been  Existing 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Errors_Existing_Name {
            get {
                return ResourceManager.GetString("Party_Customer_Errors_Existing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Name {
            get {
                return ResourceManager.GetString("Party_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Customer 的本地化字符串。
        /// </summary>
        public static string Party_Customer_New_Title {
            get {
                return ResourceManager.GetString("Party_Customer_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bill Address 的本地化字符串。
        /// </summary>
        public static string Party_Customer_TabTitle_BillAddress {
            get {
                return ResourceManager.GetString("Party_Customer_TabTitle_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer 的本地化字符串。
        /// </summary>
        public static string Party_Customer_TabTitle_Customer {
            get {
                return ResourceManager.GetString("Party_Customer_TabTitle_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship Address 的本地化字符串。
        /// </summary>
        public static string Party_Customer_TabTitle_ShipAddress {
            get {
                return ResourceManager.GetString("Party_Customer_TabTitle_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer has been updated successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Customer_Updated {
            get {
                return ResourceManager.GetString("Party_Customer_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party has been Deleted successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Deleted {
            get {
                return ResourceManager.GetString("Party_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Party 的本地化字符串。
        /// </summary>
        public static string Party_Edit_Title {
            get {
                return ResourceManager.GetString("Party_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party errors exists code userd by Customer. 的本地化字符串。
        /// </summary>
        public static string Party_Errors_Exists_Code_UserdByCustomer {
            get {
                return ResourceManager.GetString("Party_Errors_Exists_Code_UserdByCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party errors exists code userd by Region. 的本地化字符串。
        /// </summary>
        public static string Party_Errors_Exists_Code_UserdByRegion {
            get {
                return ResourceManager.GetString("Party_Errors_Exists_Code_UserdByRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party errors exists code userd by Supplier. 的本地化字符串。
        /// </summary>
        public static string Party_Errors_Exists_Code_UserdBySupplier {
            get {
                return ResourceManager.GetString("Party_Errors_Exists_Code_UserdBySupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsActive 的本地化字符串。
        /// </summary>
        public static string Party_IsActive {
            get {
                return ResourceManager.GetString("Party_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Party_Name {
            get {
                return ResourceManager.GetString("Party_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Party 的本地化字符串。
        /// </summary>
        public static string Party_New_Title {
            get {
                return ResourceManager.GetString("Party_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region Code 的本地化字符串。
        /// </summary>
        public static string Party_Region_Code {
            get {
                return ResourceManager.GetString("Party_Region_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region Name 的本地化字符串。
        /// </summary>
        public static string Party_Region_Name {
            get {
                return ResourceManager.GetString("Party_Region_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier has been added successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Added {
            get {
                return ResourceManager.GetString("Party_Supplier_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier Code 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Code {
            get {
                return ResourceManager.GetString("Party_Supplier_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier has been Deleted successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Deleted {
            get {
                return ResourceManager.GetString("Party_Supplier_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Supplier 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Edit_Title {
            get {
                return ResourceManager.GetString("Party_Supplier_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier  has  been  Existing 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Errors_Existing_Code {
            get {
                return ResourceManager.GetString("Party_Supplier_Errors_Existing_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier Name  has  been  Existing 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Errors_Existing_Name {
            get {
                return ResourceManager.GetString("Party_Supplier_Errors_Existing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier Name 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Name {
            get {
                return ResourceManager.GetString("Party_Supplier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Supplier 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_New_Title {
            get {
                return ResourceManager.GetString("Party_Supplier_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShortCode 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_ShortCode {
            get {
                return ResourceManager.GetString("Party_Supplier_ShortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bill Address 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_TabTitle_BillAddress {
            get {
                return ResourceManager.GetString("Party_Supplier_TabTitle_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship Address 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_TabTitle_ShipAddress {
            get {
                return ResourceManager.GetString("Party_Supplier_TabTitle_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_TabTitle_Supplier {
            get {
                return ResourceManager.GetString("Party_Supplier_TabTitle_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier has been updated successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Supplier_Updated {
            get {
                return ResourceManager.GetString("Party_Supplier_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party has been Updated successfully. 的本地化字符串。
        /// </summary>
        public static string Party_Updated {
            get {
                return ResourceManager.GetString("Party_Updated", resourceCulture);
            }
        }
    }
}
