//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Report {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InventoryAge {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InventoryAge() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Report.InventoryAge", typeof(InventoryAge).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string InventoryAge_itemFrom {
            get {
                return ResourceManager.GetString("InventoryAge_itemFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SAPLocation 的本地化字符串。
        /// </summary>
        public static string InventoryAge_SAPLocation
        {
            get
            {
                return ResourceManager.GetString("InventoryAge_SAPLocation", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 TypeLocation 的本地化字符串。
        /// </summary>
        public static string InventoryAge_TypeLocation
        {
            get
            {
                return ResourceManager.GetString("InventoryAge_TypeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemTo 的本地化字符串。
        /// </summary>
        public static string InventoryAge_ItemTo {
            get {
                return ResourceManager.GetString("InventoryAge_ItemTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Level {
            get {
                return ResourceManager.GetString("InventoryAge_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string InventoryAge_locationFrom {
            get {
                return ResourceManager.GetString("InventoryAge_locationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 locationTo 的本地化字符串。
        /// </summary>
        public static string InventoryAge_locationTo {
            get {
                return ResourceManager.GetString("InventoryAge_locationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 plantFrom 的本地化字符串。
        /// </summary>
        public static string InventoryAge_plantFrom {
            get {
                return ResourceManager.GetString("InventoryAge_plantFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 plantTo 的本地化字符串。
        /// </summary>
        public static string InventoryAge_plantTo {
            get {
                return ResourceManager.GetString("InventoryAge_plantTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range0 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range0 {
            get {
                return ResourceManager.GetString("InventoryAge_Range0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range1 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range1 {
            get {
                return ResourceManager.GetString("InventoryAge_Range1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range10 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range10 {
            get {
                return ResourceManager.GetString("InventoryAge_Range10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range11 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range11 {
            get {
                return ResourceManager.GetString("InventoryAge_Range11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range2 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range2 {
            get {
                return ResourceManager.GetString("InventoryAge_Range2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range3 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range3 {
            get {
                return ResourceManager.GetString("InventoryAge_Range3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range4 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range4 {
            get {
                return ResourceManager.GetString("InventoryAge_Range4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range5 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range5 {
            get {
                return ResourceManager.GetString("InventoryAge_Range5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range6 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range6 {
            get {
                return ResourceManager.GetString("InventoryAge_Range6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range7 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range7 {
            get {
                return ResourceManager.GetString("InventoryAge_Range7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range8 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range8 {
            get {
                return ResourceManager.GetString("InventoryAge_Range8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range9 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Range9 {
            get {
                return ResourceManager.GetString("InventoryAge_Range9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 regionFrom 的本地化字符串。
        /// </summary>
        public static string InventoryAge_regionFrom {
            get {
                return ResourceManager.GetString("InventoryAge_regionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 regionTo 的本地化字符串。
        /// </summary>
        public static string InventoryAge_regionTo {
            get {
                return ResourceManager.GetString("InventoryAge_regionTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        public static string InventoryAge_Day
        {
            get
            {
                return ResourceManager.GetString("InventoryAge_Day", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TheFactoryFrom 的本地化字符串。
        /// </summary>
        public static string InventoryAge_TheFactoryFrom
        {
            get
            {
                return ResourceManager.GetString("InventoryAge_TheFactoryFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TheFactoryTo 的本地化字符串。
        /// </summary>
        public static string InventoryAge_TheFactoryTo
        {
            get
            {
                return ResourceManager.GetString("InventoryAge_TheFactoryTo", resourceCulture);
            }
        }

    }
}
