//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssemblyList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssemblyList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.AssemblyList", typeof(AssemblyList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APLZL.
        /// </summary>
        public static string AssemblyList_APLZL {
            get {
                return ResourceManager.GetString("AssemblyList_APLZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUFNR.
        /// </summary>
        public static string AssemblyList_AUFNR {
            get {
                return ResourceManager.GetString("AssemblyList_AUFNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUGRU.
        /// </summary>
        public static string AssemblyList_AUGRU {
            get {
                return ResourceManager.GetString("AssemblyList_AUGRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAUGR.
        /// </summary>
        public static string AssemblyList_BAUGR {
            get {
                return ResourceManager.GetString("AssemblyList_BAUGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDMNG.
        /// </summary>
        public static string AssemblyList_BDMNG {
            get {
                return ResourceManager.GetString("AssemblyList_BDMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BISMT.
        /// </summary>
        public static string AssemblyList_BISMT {
            get {
                return ResourceManager.GetString("AssemblyList_BISMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSTNK.
        /// </summary>
        public static string AssemblyList_BSTNK {
            get {
                return ResourceManager.GetString("AssemblyList_BSTNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BWART.
        /// </summary>
        public static string AssemblyList_BWART {
            get {
                return ResourceManager.GetString("AssemblyList_BWART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHARG.
        /// </summary>
        public static string AssemblyList_CHARG {
            get {
                return ResourceManager.GetString("AssemblyList_CHARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELFLG.
        /// </summary>
        public static string AssemblyList_DELFLG {
            get {
                return ResourceManager.GetString("AssemblyList_DELFLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDP.
        /// </summary>
        public static string AssemblyList_FDP {
            get {
                return ResourceManager.GetString("AssemblyList_FDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST_FLG.
        /// </summary>
        public static string AssemblyList_FIRST_FLG {
            get {
                return ResourceManager.GetString("AssemblyList_FIRST_FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSTRS.
        /// </summary>
        public static string AssemblyList_GSTRS {
            get {
                return ResourceManager.GetString("AssemblyList_GSTRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW.
        /// </summary>
        public static string AssemblyList_GW {
            get {
                return ResourceManager.GetString("AssemblyList_GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENT.
        /// </summary>
        public static string AssemblyList_IDENT {
            get {
                return ResourceManager.GetString("AssemblyList_IDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDNRK.
        /// </summary>
        public static string AssemblyList_IDNRK {
            get {
                return ResourceManager.GetString("AssemblyList_IDNRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGORT.
        /// </summary>
        public static string AssemblyList_LGORT {
            get {
                return ResourceManager.GetString("AssemblyList_LGORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAKTX.
        /// </summary>
        public static string AssemblyList_MAKTX {
            get {
                return ResourceManager.GetString("AssemblyList_MAKTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARK.
        /// </summary>
        public static string AssemblyList_MARK {
            get {
                return ResourceManager.GetString("AssemblyList_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATNR.
        /// </summary>
        public static string AssemblyList_MATNR {
            get {
                return ResourceManager.GetString("AssemblyList_MATNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEINS.
        /// </summary>
        public static string AssemblyList_MEINS {
            get {
                return ResourceManager.GetString("AssemblyList_MEINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENGE.
        /// </summary>
        public static string AssemblyList_MENGE {
            get {
                return ResourceManager.GetString("AssemblyList_MENGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWPAGE.
        /// </summary>
        public static string AssemblyList_NEWPAGE {
            get {
                return ResourceManager.GetString("AssemblyList_NEWPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSNUM.
        /// </summary>
        public static string AssemblyList_RSNUM {
            get {
                return ResourceManager.GetString("AssemblyList_RSNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSPOS.
        /// </summary>
        public static string AssemblyList_RSPOS {
            get {
                return ResourceManager.GetString("AssemblyList_RSPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCBB.
        /// </summary>
        public static string AssemblyList_SCBB {
            get {
                return ResourceManager.GetString("AssemblyList_SCBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMARK.
        /// </summary>
        public static string AssemblyList_SMARK {
            get {
                return ResourceManager.GetString("AssemblyList_SMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STLKN.
        /// </summary>
        public static string AssemblyList_STLKN {
            get {
                return ResourceManager.GetString("AssemblyList_STLKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STLNR.
        /// </summary>
        public static string AssemblyList_STLNR {
            get {
                return ResourceManager.GetString("AssemblyList_STLNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STLTY.
        /// </summary>
        public static string AssemblyList_STLTY {
            get {
                return ResourceManager.GetString("AssemblyList_STLTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VORNR.
        /// </summary>
        public static string AssemblyList_VORNR {
            get {
                return ResourceManager.GetString("AssemblyList_VORNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKER.
        /// </summary>
        public static string AssemblyList_WORKER {
            get {
                return ResourceManager.GetString("AssemblyList_WORKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTIME.
        /// </summary>
        public static string AssemblyList_WTIME {
            get {
                return ResourceManager.GetString("AssemblyList_WTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WZ.
        /// </summary>
        public static string AssemblyList_WZ {
            get {
                return ResourceManager.GetString("AssemblyList_WZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOPDS.
        /// </summary>
        public static string AssemblyList_ZOPDS {
            get {
                return ResourceManager.GetString("AssemblyList_ZOPDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOPID.
        /// </summary>
        public static string AssemblyList_ZOPID {
            get {
                return ResourceManager.GetString("AssemblyList_ZOPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZZVP.
        /// </summary>
        public static string AssemblyList_ZZVP {
            get {
                return ResourceManager.GetString("AssemblyList_ZZVP", resourceCulture);
            }
        }
    }
}
