//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IpDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IpDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.IpDetail", typeof(IpDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string IpDetail_Container {
            get {
                return ResourceManager.GetString("IpDetail_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainerDescription.
        /// </summary>
        public static string IpDetail_ContainerDescription {
            get {
                return ResourceManager.GetString("IpDetail_ContainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentReceiveQty.
        /// </summary>
        public static string IpDetail_CurrentReceiveQty {
            get {
                return ResourceManager.GetString("IpDetail_CurrentReceiveQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalOrderNo.
        /// </summary>
        public static string IpDetail_ExternalOrderNo {
            get {
                return ResourceManager.GetString("IpDetail_ExternalOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalSequence.
        /// </summary>
        public static string IpDetail_ExternalSequence {
            get {
                return ResourceManager.GetString("IpDetail_ExternalSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuQty.
        /// </summary>
        public static string IpDetail_HuQty {
            get {
                return ResourceManager.GetString("IpDetail_HuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpDetailType.
        /// </summary>
        public static string IpDetail_IpDetailType {
            get {
                return ResourceManager.GetString("IpDetail_IpDetailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpNo.
        /// </summary>
        public static string IpDetail_IpNo {
            get {
                return ResourceManager.GetString("IpDetail_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCancel.
        /// </summary>
        public static string IpDetail_IsCancel {
            get {
                return ResourceManager.GetString("IpDetail_IsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsClose.
        /// </summary>
        public static string IpDetail_IsClose {
            get {
                return ResourceManager.GetString("IpDetail_IsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsConfirm.
        /// </summary>
        public static string IpDetail_IsConfirm {
            get {
                return ResourceManager.GetString("IpDetail_IsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInspect.
        /// </summary>
        public static string IpDetail_IsInspect {
            get {
                return ResourceManager.GetString("IpDetail_IsInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string IpDetail_Item {
            get {
                return ResourceManager.GetString("IpDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string IpDetail_ItemDescription {
            get {
                return ResourceManager.GetString("IpDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFromName.
        /// </summary>
        public static string IpDetail_LocationFromName {
            get {
                return ResourceManager.GetString("IpDetail_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string IpDetail_LocationTo {
            get {
                return ResourceManager.GetString("IpDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationToName.
        /// </summary>
        public static string IpDetail_LocationToName {
            get {
                return ResourceManager.GetString("IpDetail_LocationToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string IpDetail_LotNo {
            get {
                return ResourceManager.GetString("IpDetail_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string IpDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("IpDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetailId.
        /// </summary>
        public static string IpDetail_OrderNo {
            get {
                return ResourceManager.GetString("IpDetail_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string IpDetail_Qty {
            get {
                return ResourceManager.GetString("IpDetail_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedQty.
        /// </summary>
        public static string IpDetail_ReceivedQty {
            get {
                return ResourceManager.GetString("IpDetail_ReceivedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefItemCode.
        /// </summary>
        public static string IpDetail_RefItemCode {
            get {
                return ResourceManager.GetString("IpDetail_RefItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string IpDetail_Sequence {
            get {
                return ResourceManager.GetString("IpDetail_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierLotNo.
        /// </summary>
        public static string IpDetail_SupplierLotNo {
            get {
                return ResourceManager.GetString("IpDetail_SupplierLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpDetail.
        /// </summary>
        public static string IpDetail_Title {
            get {
                return ResourceManager.GetString("IpDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string IpDetail_Type {
            get {
                return ResourceManager.GetString("IpDetail_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string IpDetail_UnitCount {
            get {
                return ResourceManager.GetString("IpDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCountDescription.
        /// </summary>
        public static string IpDetail_UnitCountDescription {
            get {
                return ResourceManager.GetString("IpDetail_UnitCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string IpDetail_Uom {
            get {
                return ResourceManager.GetString("IpDetail_Uom", resourceCulture);
            }
        }
    }
}
