//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.OrderDetail", typeof(OrderDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackOrderQty.
        /// </summary>
        public static string OrderDetail_BackOrderQty {
            get {
                return ResourceManager.GetString("OrderDetail_BackOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillAddress.
        /// </summary>
        public static string OrderDetail_BillAddress {
            get {
                return ResourceManager.GetString("OrderDetail_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillAddressDescription.
        /// </summary>
        public static string OrderDetail_BillAddressDescription {
            get {
                return ResourceManager.GetString("OrderDetail_BillAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillTerm.
        /// </summary>
        public static string OrderDetail_BillTerm {
            get {
                return ResourceManager.GetString("OrderDetail_BillTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinTo.
        /// </summary>
        public static string OrderDetail_BinTo {
            get {
                return ResourceManager.GetString("OrderDetail_BinTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bom.
        /// </summary>
        public static string OrderDetail_Bom {
            get {
                return ResourceManager.GetString("OrderDetail_Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BomDetail.
        /// </summary>
        public static string OrderDetail_BomDetail_Title_View {
            get {
                return ResourceManager.GetString("OrderDetail_BomDetail_Title_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string OrderDetail_Container {
            get {
                return ResourceManager.GetString("OrderDetail_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainerDescrip.
        /// </summary>
        public static string OrderDetail_ContainerDescription {
            get {
                return ResourceManager.GetString("OrderDetail_ContainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPTime.
        /// </summary>
        public static string OrderDetail_CPTime {
            get {
                return ResourceManager.GetString("OrderDetail_CPTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string OrderDetail_CreateDate {
            get {
                return ResourceManager.GetString("OrderDetail_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string OrderDetail_CreateUserName {
            get {
                return ResourceManager.GetString("OrderDetail_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPickListQty.
        /// </summary>
        public static string OrderDetail_CurrentPickListQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentPickListQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPickQty.
        /// </summary>
        public static string OrderDetail_CurrentPickQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentPickQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentReceiveQty.
        /// </summary>
        public static string OrderDetail_CurrentReceiveQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentReceiveQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentRecQty.
        /// </summary>
        public static string OrderDetail_CurrentRecQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentRecQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentScrapQty.
        /// </summary>
        public static string OrderDetail_CurrentScrapQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentScrapQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentShipQty.
        /// </summary>
        public static string OrderDetail_CurrentShipQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentShipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DemandDate.
        /// </summary>
        public static string OrderDetail_DemandDate {
            get {
                return ResourceManager.GetString("OrderDetail_DemandDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DemandQty.
        /// </summary>
        public static string OrderDetail_DemandQty {
            get {
                return ResourceManager.GetString("OrderDetail_DemandQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalOrderNo.
        /// </summary>
        public static string OrderDetail_ExternalOrderNo {
            get {
                return ResourceManager.GetString("OrderDetail_ExternalOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalOrderNo.
        /// </summary>
        public static string OrderDetail_ExternalOrderNo_Export {
            get {
                return ResourceManager.GetString("OrderDetail_ExternalOrderNo_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalOrderNo_ExportDet.
        /// </summary>
        public static string OrderDetail_ExternalOrderNo_ExportDet {
            get {
                return ResourceManager.GetString("OrderDetail_ExternalOrderNo_ExportDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalSequence.
        /// </summary>
        public static string OrderDetail_ExternalSequence {
            get {
                return ResourceManager.GetString("OrderDetail_ExternalSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalSequence_ExportDet.
        /// </summary>
        public static string OrderDetail_ExternalSequence_ExportDet {
            get {
                return ResourceManager.GetString("OrderDetail_ExternalSequence_ExportDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string OrderDetail_Flow {
            get {
                return ResourceManager.GetString("OrderDetail_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForecastQty.
        /// </summary>
        public static string OrderDetail_ForecastQty {
            get {
                return ResourceManager.GetString("OrderDetail_ForecastQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuQty.
        /// </summary>
        public static string OrderDetail_HuQty {
            get {
                return ResourceManager.GetString("OrderDetail_HuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string OrderDetail_Id {
            get {
                return ResourceManager.GetString("OrderDetail_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryQty.
        /// </summary>
        public static string OrderDetail_InventoryQty {
            get {
                return ResourceManager.GetString("OrderDetail_InventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCreateSeq.
        /// </summary>
        public static string OrderDetail_IsCreateSeq {
            get {
                return ResourceManager.GetString("OrderDetail_IsCreateSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsIncludeTax.
        /// </summary>
        public static string OrderDetail_IsIncludeTax {
            get {
                return ResourceManager.GetString("OrderDetail_IsIncludeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInspect.
        /// </summary>
        public static string OrderDetail_IsInspect {
            get {
                return ResourceManager.GetString("OrderDetail_IsInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsProvisionalEstimate.
        /// </summary>
        public static string OrderDetail_IsProvisionalEstimate {
            get {
                return ResourceManager.GetString("OrderDetail_IsProvisionalEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string OrderDetail_Item {
            get {
                return ResourceManager.GetString("OrderDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string OrderDetail_ItemDescription {
            get {
                return ResourceManager.GetString("OrderDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string OrderDetail_LastModifyDate {
            get {
                return ResourceManager.GetString("OrderDetail_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string OrderDetail_LastModifyUserName {
            get {
                return ResourceManager.GetString("OrderDetail_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDays.
        /// </summary>
        public static string OrderDetail_ListDays {
            get {
                return ResourceManager.GetString("OrderDetail_ListDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string OrderDetail_LocationFrom {
            get {
                return ResourceManager.GetString("OrderDetail_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFromName.
        /// </summary>
        public static string OrderDetail_LocationFromName {
            get {
                return ResourceManager.GetString("OrderDetail_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationQty.
        /// </summary>
        public static string OrderDetail_LocationQty {
            get {
                return ResourceManager.GetString("OrderDetail_LocationQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string OrderDetail_LocationTo {
            get {
                return ResourceManager.GetString("OrderDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationToName.
        /// </summary>
        public static string OrderDetail_LocationToName {
            get {
                return ResourceManager.GetString("OrderDetail_LocationToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string OrderDetail_LotNo {
            get {
                return ResourceManager.GetString("OrderDetail_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string OrderDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("OrderDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinUnitCount.
        /// </summary>
        public static string OrderDetail_MinUnitCount {
            get {
                return ResourceManager.GetString("OrderDetail_MinUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string OrderDetail_Operation_Title_View {
            get {
                return ResourceManager.GetString("OrderDetail_Operation_Title_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpRef.
        /// </summary>
        public static string OrderDetail_OpRef {
            get {
                return ResourceManager.GetString("OrderDetail_OpRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetail.
        /// </summary>
        public static string OrderDetail_OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail_OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetails.
        /// </summary>
        public static string OrderDetail_OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetail_OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderedQty.
        /// </summary>
        public static string OrderDetail_OrderedQty {
            get {
                return ResourceManager.GetString("OrderDetail_OrderedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderedQtyReturn.
        /// </summary>
        public static string OrderDetail_OrderedQtyReturn {
            get {
                return ResourceManager.GetString("OrderDetail_OrderedQtyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string OrderDetail_OrderNo {
            get {
                return ResourceManager.GetString("OrderDetail_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom.
        /// </summary>
        public static string OrderDetail_PartyFrom {
            get {
                return ResourceManager.GetString("OrderDetail_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo.
        /// </summary>
        public static string OrderDetail_PartyTo {
            get {
                return ResourceManager.GetString("OrderDetail_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickedQty.
        /// </summary>
        public static string OrderDetail_PickedQty {
            get {
                return ResourceManager.GetString("OrderDetail_PickedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceList.
        /// </summary>
        public static string OrderDetail_PriceList {
            get {
                return ResourceManager.GetString("OrderDetail_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionScan.
        /// </summary>
        public static string OrderDetail_ProductionScan {
            get {
                return ResourceManager.GetString("OrderDetail_ProductionScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLineFacility.
        /// </summary>
        public static string OrderDetail_ProductLineFacility {
            get {
                return ResourceManager.GetString("OrderDetail_ProductLineFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveDate.
        /// </summary>
        public static string OrderDetail_ReceiveDate {
            get {
                return ResourceManager.GetString("OrderDetail_ReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedQty.
        /// </summary>
        public static string OrderDetail_ReceivedQty {
            get {
                return ResourceManager.GetString("OrderDetail_ReceivedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveLotSize.
        /// </summary>
        public static string OrderDetail_ReceiveLotSize {
            get {
                return ResourceManager.GetString("OrderDetail_ReceiveLotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string OrderDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("OrderDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Qty.
        /// </summary>
        public static string OrderDetail_RejectedQty {
            get {
                return ResourceManager.GetString("OrderDetail_RejectedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string OrderDetail_Remark {
            get {
                return ResourceManager.GetString("OrderDetail_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Qty.
        /// </summary>
        public static string OrderDetail_RequiredQty {
            get {
                return ResourceManager.GetString("OrderDetail_RequiredQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing.
        /// </summary>
        public static string OrderDetail_Routing {
            get {
                return ResourceManager.GetString("OrderDetail_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetail Saved..
        /// </summary>
        public static string OrderDetail_Saved {
            get {
                return ResourceManager.GetString("OrderDetail_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleLineNo.
        /// </summary>
        public static string OrderDetail_ScheduleLineNo {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleLineSeq.
        /// </summary>
        public static string OrderDetail_ScheduleLineSeq {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleLineSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleType.
        /// </summary>
        public static string OrderDetail_ScheduleType {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string OrderDetail_ScheduleType_All {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapQty.
        /// </summary>
        public static string OrderDetail_ScrapQty {
            get {
                return ResourceManager.GetString("OrderDetail_ScrapQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string OrderDetail_Sequence {
            get {
                return ResourceManager.GetString("OrderDetail_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedQty.
        /// </summary>
        public static string OrderDetail_ShippedQty {
            get {
                return ResourceManager.GetString("OrderDetail_ShippedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetail_ShipQty.
        /// </summary>
        public static string OrderDetail_ShipQty {
            get {
                return ResourceManager.GetString("OrderDetail_ShipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierLotNo.
        /// </summary>
        public static string OrderDetail_SupplierLotNo {
            get {
                return ResourceManager.GetString("OrderDetail_SupplierLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string OrderDetail_Tax {
            get {
                return ResourceManager.GetString("OrderDetail_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax_ScheduLine.
        /// </summary>
        public static string OrderDetail_Tax_ScheduLine {
            get {
                return ResourceManager.GetString("OrderDetail_Tax_ScheduLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetail.
        /// </summary>
        public static string OrderDetail_Title {
            get {
                return ResourceManager.GetString("OrderDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToShipQty.
        /// </summary>
        public static string OrderDetail_ToShipQty {
            get {
                return ResourceManager.GetString("OrderDetail_ToShipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalOrderQty.
        /// </summary>
        public static string OrderDetail_TotalOrderQty {
            get {
                return ResourceManager.GetString("OrderDetail_TotalOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCDesc.
        /// </summary>
        public static string OrderDetail_UCDesc {
            get {
                return ResourceManager.GetString("OrderDetail_UCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string OrderDetail_UnitCount {
            get {
                return ResourceManager.GetString("OrderDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCountDescrip.
        /// </summary>
        public static string OrderDetail_UnitCountDescription {
            get {
                return ResourceManager.GetString("OrderDetail_UnitCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice.
        /// </summary>
        public static string OrderDetail_UnitPrice {
            get {
                return ResourceManager.GetString("OrderDetail_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitQty.
        /// </summary>
        public static string OrderDetail_UnitQty {
            get {
                return ResourceManager.GetString("OrderDetail_UnitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string OrderDetail_Uom {
            get {
                return ResourceManager.GetString("OrderDetail_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OrderDetail_Version {
            get {
                return ResourceManager.GetString("OrderDetail_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMSSeq.
        /// </summary>
        public static string OrderDetail_WMSSeq {
            get {
                return ResourceManager.GetString("OrderDetail_WMSSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZENGINE.
        /// </summary>
        public static string OrderDetail_ZENGINE {
            get {
                return ResourceManager.GetString("OrderDetail_ZENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpCreateDate.
        /// </summary>
        public static string OrderMaster_IpCreateDate {
            get {
                return ResourceManager.GetString("OrderMaster_IpCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalOrderNo.
        /// </summary>
        public static string SeqOrderChange_ExternalOrderNo {
            get {
                return ResourceManager.GetString("SeqOrderChange_ExternalOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalSequence.
        /// </summary>
        public static string SeqOrderChange_ExternalSequence {
            get {
                return ResourceManager.GetString("SeqOrderChange_ExternalSequence", resourceCulture);
            }
        }
    }
}
