//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickResult() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.PickResult", typeof(PickResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asn No..
        /// </summary>
        public static string PickResult_AsnNo {
            get {
                return ResourceManager.GetString("PickResult_AsnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu Qty.
        /// </summary>
        public static string PickResult_HuQty {
            get {
                return ResourceManager.GetString("PickResult_HuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string PickResult_Memo {
            get {
                return ResourceManager.GetString("PickResult_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick date.
        /// </summary>
        public static string PickResult_PickDate {
            get {
                return ResourceManager.GetString("PickResult_PickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked Hu.
        /// </summary>
        public static string PickResult_PickedHu {
            get {
                return ResourceManager.GetString("PickResult_PickedHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked Qty.
        /// </summary>
        public static string PickResult_PickedQty {
            get {
                return ResourceManager.GetString("PickResult_PickedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        public static string PickResult_Picker {
            get {
                return ResourceManager.GetString("PickResult_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Id.
        /// </summary>
        public static string PickResult_PickId {
            get {
                return ResourceManager.GetString("PickResult_PickId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Id.
        /// </summary>
        public static string PickResult_ResultId {
            get {
                return ResourceManager.GetString("PickResult_ResultId", resourceCulture);
            }
        }
    }
}
