//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickTask {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickTask() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.PickTask", typeof(PickTask).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseUom.
        /// </summary>
        public static string PickTask_BaseUom {
            get {
                return ResourceManager.GetString("PickTask_BaseUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string PickTask_ButtonAssign {
            get {
                return ResourceManager.GetString("PickTask_ButtonAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string PickTask_ButtonHold {
            get {
                return ResourceManager.GetString("PickTask_ButtonHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PickTask_ButtonPrint {
            get {
                return ResourceManager.GetString("PickTask_ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhold.
        /// </summary>
        public static string PickTask_ButtonUnhold {
            get {
                return ResourceManager.GetString("PickTask_ButtonUnhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string PickTask_Flow {
            get {
                return ResourceManager.GetString("PickTask_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow description.
        /// </summary>
        public static string PickTask_FlowDesc {
            get {
                return ResourceManager.GetString("PickTask_FlowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include finished.
        /// </summary>
        public static string PickTask_IncludeFinished {
            get {
                return ResourceManager.GetString("PickTask_IncludeFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is hold.
        /// </summary>
        public static string PickTask_IsHold {
            get {
                return ResourceManager.GetString("PickTask_IsHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string PickTask_Item {
            get {
                return ResourceManager.GetString("PickTask_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item description.
        /// </summary>
        public static string PickTask_ItemDesc {
            get {
                return ResourceManager.GetString("PickTask_ItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location From.
        /// </summary>
        public static string PickTask_LocationFrom {
            get {
                return ResourceManager.GetString("PickTask_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location From Name.
        /// </summary>
        public static string PickTask_LocationFromName {
            get {
                return ResourceManager.GetString("PickTask_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location To.
        /// </summary>
        public static string PickTask_LocationTo {
            get {
                return ResourceManager.GetString("PickTask_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location To Name.
        /// </summary>
        public static string PickTask_LocationToName {
            get {
                return ResourceManager.GetString("PickTask_LocationToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string PickTask_Memo {
            get {
                return ResourceManager.GetString("PickTask_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New picker.
        /// </summary>
        public static string PickTask_NewPicker {
            get {
                return ResourceManager.GetString("PickTask_NewPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered qty.
        /// </summary>
        public static string PickTask_OrderedQty {
            get {
                return ResourceManager.GetString("PickTask_OrderedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No..
        /// </summary>
        public static string PickTask_OrderNo {
            get {
                return ResourceManager.GetString("PickTask_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party From.
        /// </summary>
        public static string PickTask_PartyFrom {
            get {
                return ResourceManager.GetString("PickTask_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party From Name.
        /// </summary>
        public static string PickTask_PartyFromName {
            get {
                return ResourceManager.GetString("PickTask_PartyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party To.
        /// </summary>
        public static string PickTask_PartyTo {
            get {
                return ResourceManager.GetString("PickTask_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party To Name.
        /// </summary>
        public static string PickTask_PartyToName {
            get {
                return ResourceManager.GetString("PickTask_PartyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked qty.
        /// </summary>
        public static string PickTask_PickedQty {
            get {
                return ResourceManager.GetString("PickTask_PickedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        public static string PickTask_Picker {
            get {
                return ResourceManager.GetString("PickTask_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickTask Id.
        /// </summary>
        public static string PickTask_PickId {
            get {
                return ResourceManager.GetString("PickTask_PickId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print count.
        /// </summary>
        public static string PickTask_PrintCount {
            get {
                return ResourceManager.GetString("PickTask_PrintCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string PickTask_ReleaseDate {
            get {
                return ResourceManager.GetString("PickTask_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate To.
        /// </summary>
        public static string PickTask_ReleaseEnd {
            get {
                return ResourceManager.GetString("PickTask_ReleaseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate From.
        /// </summary>
        public static string PickTask_ReleaseStart {
            get {
                return ResourceManager.GetString("PickTask_ReleaseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedQty.
        /// </summary>
        public static string PickTask_ShippedQty {
            get {
                return ResourceManager.GetString("PickTask_ShippedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hold.
        /// </summary>
        public static string PickTask_ShowHold {
            get {
                return ResourceManager.GetString("PickTask_ShowHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string PickTask_Supplier {
            get {
                return ResourceManager.GetString("PickTask_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier name.
        /// </summary>
        public static string PickTask_SupplierName {
            get {
                return ResourceManager.GetString("PickTask_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Count.
        /// </summary>
        public static string PickTask_UnitCount {
            get {
                return ResourceManager.GetString("PickTask_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string PickTask_Uom {
            get {
                return ResourceManager.GetString("PickTask_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTime To.
        /// </summary>
        public static string PickTask_WindowEnd {
            get {
                return ResourceManager.GetString("PickTask_WindowEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTime From.
        /// </summary>
        public static string PickTask_WindowStart {
            get {
                return ResourceManager.GetString("PickTask_WindowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window time.
        /// </summary>
        public static string PickTask_WindowTime {
            get {
                return ResourceManager.GetString("PickTask_WindowTime", resourceCulture);
            }
        }
    }
}
