//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickListMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickListMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.PickListMaster", typeof(PickListMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsnTemplate.
        /// </summary>
        public static string PickListMaster_AsnTemplate {
            get {
                return ResourceManager.GetString("PickListMaster_AsnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelDate.
        /// </summary>
        public static string PickListMaster_CancelDate {
            get {
                return ResourceManager.GetString("PickListMaster_CancelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickListMaster Canceled.
        /// </summary>
        public static string PickListMaster_Canceled {
            get {
                return ResourceManager.GetString("PickListMaster_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelUserName.
        /// </summary>
        public static string PickListMaster_CancelUserName {
            get {
                return ResourceManager.GetString("PickListMaster_CancelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDate.
        /// </summary>
        public static string PickListMaster_CloseDate {
            get {
                return ResourceManager.GetString("PickListMaster_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseUserName.
        /// </summary>
        public static string PickListMaster_CloseUserName {
            get {
                return ResourceManager.GetString("PickListMaster_CloseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteDate.
        /// </summary>
        public static string PickListMaster_CompleteDate {
            get {
                return ResourceManager.GetString("PickListMaster_CompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteUserName.
        /// </summary>
        public static string PickListMaster_CompleteUserName {
            get {
                return ResourceManager.GetString("PickListMaster_CompleteUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickListMaster Created.
        /// </summary>
        public static string PickListMaster_Created {
            get {
                return ResourceManager.GetString("PickListMaster_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string PickListMaster_CreateDate {
            get {
                return ResourceManager.GetString("PickListMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string PickListMaster_CreateUserName {
            get {
                return ResourceManager.GetString("PickListMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryGroup.
        /// </summary>
        public static string PickListMaster_DeliveryGroup {
            get {
                return ResourceManager.GetString("PickListMaster_DeliveryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string PickListMaster_Dock {
            get {
                return ResourceManager.GetString("PickListMaster_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PickListMaster.
        /// </summary>
        public static string PickListMaster_Edit_Title {
            get {
                return ResourceManager.GetString("PickListMaster_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDate.
        /// </summary>
        public static string PickListMaster_EffectiveDate {
            get {
                return ResourceManager.GetString("PickListMaster_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string PickListMaster_EndDate {
            get {
                return ResourceManager.GetString("PickListMaster_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string PickListMaster_Flow {
            get {
                return ResourceManager.GetString("PickListMaster_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuTemplate.
        /// </summary>
        public static string PickListMaster_HuTemplate {
            get {
                return ResourceManager.GetString("PickListMaster_HuTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAsnUniqueReceive.
        /// </summary>
        public static string PickListMaster_IsAsnUniqueReceive {
            get {
                return ResourceManager.GetString("PickListMaster_IsAsnUniqueReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoReceive.
        /// </summary>
        public static string PickListMaster_IsAutoReceive {
            get {
                return ResourceManager.GetString("PickListMaster_IsAutoReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCheckPartyFromAuthority.
        /// </summary>
        public static string PickListMaster_IsCheckPartyFromAuthority {
            get {
                return ResourceManager.GetString("PickListMaster_IsCheckPartyFromAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCheckPartyToAuthority.
        /// </summary>
        public static string PickListMaster_IsCheckPartyToAuthority {
            get {
                return ResourceManager.GetString("PickListMaster_IsCheckPartyToAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintAsn.
        /// </summary>
        public static string PickListMaster_IsPrintAsn {
            get {
                return ResourceManager.GetString("PickListMaster_IsPrintAsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintReceipt.
        /// </summary>
        public static string PickListMaster_IsPrintReceipt {
            get {
                return ResourceManager.GetString("PickListMaster_IsPrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveExceed.
        /// </summary>
        public static string PickListMaster_IsReceiveExceed {
            get {
                return ResourceManager.GetString("PickListMaster_IsReceiveExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveFifo.
        /// </summary>
        public static string PickListMaster_IsReceiveFifo {
            get {
                return ResourceManager.GetString("PickListMaster_IsReceiveFifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveFulfillUC.
        /// </summary>
        public static string PickListMaster_IsReceiveFulfillUC {
            get {
                return ResourceManager.GetString("PickListMaster_IsReceiveFulfillUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveScanHu.
        /// </summary>
        public static string PickListMaster_IsReceiveScanHu {
            get {
                return ResourceManager.GetString("PickListMaster_IsReceiveScanHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string PickListMaster_Item {
            get {
                return ResourceManager.GetString("PickListMaster_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string PickListMaster_LastModifyDate {
            get {
                return ResourceManager.GetString("PickListMaster_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string PickListMaster_LastModifyUserName {
            get {
                return ResourceManager.GetString("PickListMaster_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderType.
        /// </summary>
        public static string PickListMaster_OrderType {
            get {
                return ResourceManager.GetString("PickListMaster_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom.
        /// </summary>
        public static string PickListMaster_PartyFrom {
            get {
                return ResourceManager.GetString("PickListMaster_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFromName.
        /// </summary>
        public static string PickListMaster_PartyFromName {
            get {
                return ResourceManager.GetString("PickListMaster_PartyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo.
        /// </summary>
        public static string PickListMaster_PartyTo {
            get {
                return ResourceManager.GetString("PickListMaster_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyToName.
        /// </summary>
        public static string PickListMaster_PartyToName {
            get {
                return ResourceManager.GetString("PickListMaster_PartyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickList.
        /// </summary>
        public static string PickListMaster_PickList_Title {
            get {
                return ResourceManager.GetString("PickListMaster_PickList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickListNo.
        /// </summary>
        public static string PickListMaster_PickListNo {
            get {
                return ResourceManager.GetString("PickListMaster_PickListNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickListResult Deleted.
        /// </summary>
        public static string PickListMaster_PickListResultDeleted {
            get {
                return ResourceManager.GetString("PickListMaster_PickListResultDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptTemplate.
        /// </summary>
        public static string PickListMaster_ReceiptTemplate {
            get {
                return ResourceManager.GetString("PickListMaster_ReceiptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFrom.
        /// </summary>
        public static string PickListMaster_ShipFrom {
            get {
                return ResourceManager.GetString("PickListMaster_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromAddress.
        /// </summary>
        public static string PickListMaster_ShipFromAddress {
            get {
                return ResourceManager.GetString("PickListMaster_ShipFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromCell.
        /// </summary>
        public static string PickListMaster_ShipFromCell {
            get {
                return ResourceManager.GetString("PickListMaster_ShipFromCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string PickListMaster_ShipFromContact {
            get {
                return ResourceManager.GetString("PickListMaster_ShipFromContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromTel.
        /// </summary>
        public static string PickListMaster_ShipFromTel {
            get {
                return ResourceManager.GetString("PickListMaster_ShipFromTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickListMaster Shipped.
        /// </summary>
        public static string PickListMaster_Shipped {
            get {
                return ResourceManager.GetString("PickListMaster_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTo.
        /// </summary>
        public static string PickListMaster_ShipTo {
            get {
                return ResourceManager.GetString("PickListMaster_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToAddress.
        /// </summary>
        public static string PickListMaster_ShipToAddress {
            get {
                return ResourceManager.GetString("PickListMaster_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToCell.
        /// </summary>
        public static string PickListMaster_ShipToCell {
            get {
                return ResourceManager.GetString("PickListMaster_ShipToCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToContact.
        /// </summary>
        public static string PickListMaster_ShipToContact {
            get {
                return ResourceManager.GetString("PickListMaster_ShipToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToTel.
        /// </summary>
        public static string PickListMaster_ShipToTel {
            get {
                return ResourceManager.GetString("PickListMaster_ShipToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string PickListMaster_StartDate {
            get {
                return ResourceManager.GetString("PickListMaster_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickListMaster Started.
        /// </summary>
        public static string PickListMaster_Started {
            get {
                return ResourceManager.GetString("PickListMaster_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        public static string PickListMaster_StartTime {
            get {
                return ResourceManager.GetString("PickListMaster_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartUserName.
        /// </summary>
        public static string PickListMaster_StartUserName {
            get {
                return ResourceManager.GetString("PickListMaster_StartUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PickListMaster_Status {
            get {
                return ResourceManager.GetString("PickListMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTime.
        /// </summary>
        public static string PickListMaster_WindowTime {
            get {
                return ResourceManager.GetString("PickListMaster_WindowTime", resourceCulture);
            }
        }
    }
}
