//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceiptDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.ReceiptDetail", typeof(ReceiptDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpDetailType.
        /// </summary>
        public static string ReceiptDetail_IpDetailType {
            get {
                return ResourceManager.GetString("ReceiptDetail_IpDetailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpNo.
        /// </summary>
        public static string ReceiptDetail_IpNo {
            get {
                return ResourceManager.GetString("ReceiptDetail_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ReceiptDetail_Item {
            get {
                return ResourceManager.GetString("ReceiptDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string ReceiptDetail_ItemDescription {
            get {
                return ResourceManager.GetString("ReceiptDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string ReceiptDetail_LocationTo {
            get {
                return ResourceManager.GetString("ReceiptDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string ReceiptDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("ReceiptDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string ReceiptDetail_OrderNo {
            get {
                return ResourceManager.GetString("ReceiptDetail_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo_Production.
        /// </summary>
        public static string ReceiptDetail_OrderNo_Production {
            get {
                return ResourceManager.GetString("ReceiptDetail_OrderNo_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptNo.
        /// </summary>
        public static string ReceiptDetail_ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptDetail_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Qty.
        /// </summary>
        public static string ReceiptDetail_ReceivedQty {
            get {
                return ResourceManager.GetString("ReceiptDetail_ReceivedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Item Code.
        /// </summary>
        public static string ReceiptDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("ReceiptDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string ReceiptDetail_Sequence {
            get {
                return ResourceManager.GetString("ReceiptDetail_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string ReceiptDetail_UnitCount {
            get {
                return ResourceManager.GetString("ReceiptDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string ReceiptDetail_Uom {
            get {
                return ResourceManager.GetString("ReceiptDetail_Uom", resourceCulture);
            }
        }
    }
}
