//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceiptMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.ReceiptMaster", typeof(ReceiptMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt line can not be empty..
        /// </summary>
        public static string Errors_ReceiptDetailIsEmpty {
            get {
                return ResourceManager.GetString("Errors_ReceiptDetailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelReason.
        /// </summary>
        public static string ReceiptMaster_CancelReason {
            get {
                return ResourceManager.GetString("ReceiptMaster_CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string ReceiptMaster_CreateDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string ReceiptMaster_CreateUserName {
            get {
                return ResourceManager.GetString("ReceiptMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string ReceiptMaster_Dock {
            get {
                return ResourceManager.GetString("ReceiptMaster_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string ReceiptMaster_EndDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalReceiptNo.
        /// </summary>
        public static string ReceiptMaster_ExternalReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_ExternalReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string ReceiptMaster_Flow {
            get {
                return ResourceManager.GetString("ReceiptMaster_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpNo.
        /// </summary>
        public static string ReceiptMaster_IpNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCheckPartyFromAuthority.
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyFromAuthority {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyFromAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCheckPartyFromAuthority_Customer.
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyFromAuthority_Customer {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyFromAuthority_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCheckPartyFromAuthority_Procurement.
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyFromAuthority_Procurement {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyFromAuthority_Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCheckPartyToAuthority.
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyToAuthority {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyToAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintReceipt.
        /// </summary>
        public static string ReceiptMaster_IsPrintReceipt {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsPrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveScanHu.
        /// </summary>
        public static string ReceiptMaster_IsReceiveScanHu {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsReceiveScanHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ReceiptMaster_Item {
            get {
                return ResourceManager.GetString("ReceiptMaster_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string ReceiptMaster_LastModifyDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string ReceiptMaster_LastModifyUserName {
            get {
                return ResourceManager.GetString("ReceiptMaster_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderSubType.
        /// </summary>
        public static string ReceiptMaster_OrderSubType {
            get {
                return ResourceManager.GetString("ReceiptMaster_OrderSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderType.
        /// </summary>
        public static string ReceiptMaster_OrderType {
            get {
                return ResourceManager.GetString("ReceiptMaster_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom.
        /// </summary>
        public static string ReceiptMaster_PartyFrom {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom_Procurement.
        /// </summary>
        public static string ReceiptMaster_PartyFrom_Procurement {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyFrom_Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFromName.
        /// </summary>
        public static string ReceiptMaster_PartyFromName {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo.
        /// </summary>
        public static string ReceiptMaster_PartyTo {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo_Procurement.
        /// </summary>
        public static string ReceiptMaster_PartyTo_Procurement {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyTo_Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyToName.
        /// </summary>
        public static string ReceiptMaster_PartyToName {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptNo.
        /// </summary>
        public static string ReceiptMaster_ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptTemplate.
        /// </summary>
        public static string ReceiptMaster_ReceiptTemplate {
            get {
                return ResourceManager.GetString("ReceiptMaster_ReceiptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFrom.
        /// </summary>
        public static string ReceiptMaster_ShipFrom {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromAddress.
        /// </summary>
        public static string ReceiptMaster_ShipFromAddress {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromContact.
        /// </summary>
        public static string ReceiptMaster_ShipFromContact {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFromContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromTel.
        /// </summary>
        public static string ReceiptMaster_ShipFromTel {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFromTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTo.
        /// </summary>
        public static string ReceiptMaster_ShipTo {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToAddress.
        /// </summary>
        public static string ReceiptMaster_ShipToAddress {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToContact.
        /// </summary>
        public static string ReceiptMaster_ShipToContact {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToTel.
        /// </summary>
        public static string ReceiptMaster_ShipToTel {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string ReceiptMaster_StartDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReceiptMaster_Status {
            get {
                return ResourceManager.GetString("ReceiptMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReceiptMaster_StatusDescription {
            get {
                return ResourceManager.GetString("ReceiptMaster_StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpDetailType.
        /// </summary>
        public static string ReceiptMaster_Type {
            get {
                return ResourceManager.GetString("ReceiptMaster_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMSNo.
        /// </summary>
        public static string ReceiptMaster_WMSNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_WMSNo", resourceCulture);
            }
        }
    }
}
