//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TyreOrderDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TyreOrderDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.TyreOrderDetail", typeof(TyreOrderDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteDate.
        /// </summary>
        public static string TyreOrderDetail_CompleteDate {
            get {
                return ResourceManager.GetString("TyreOrderDetail_CompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string TyreOrderDetail_Flow {
            get {
                return ResourceManager.GetString("TyreOrderDetail_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowDescription.
        /// </summary>
        public static string TyreOrderDetail_FlowDescription {
            get {
                return ResourceManager.GetString("TyreOrderDetail_FlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string TyreOrderDetail_Item {
            get {
                return ResourceManager.GetString("TyreOrderDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string TyreOrderDetail_ItemDescription {
            get {
                return ResourceManager.GetString("TyreOrderDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string TyreOrderDetail_LastModifyDate {
            get {
                return ResourceManager.GetString("TyreOrderDetail_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string TyreOrderDetail_LastModifyUserName {
            get {
                return ResourceManager.GetString("TyreOrderDetail_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string TyreOrderDetail_LocationFrom {
            get {
                return ResourceManager.GetString("TyreOrderDetail_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string TyreOrderDetail_LocationTo {
            get {
                return ResourceManager.GetString("TyreOrderDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderedQty.
        /// </summary>
        public static string TyreOrderDetail_OrderedQty {
            get {
                return ResourceManager.GetString("TyreOrderDetail_OrderedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string TyreOrderDetail_OrderNo {
            get {
                return ResourceManager.GetString("TyreOrderDetail_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProdLine.
        /// </summary>
        public static string TyreOrderDetail_ProdLine {
            get {
                return ResourceManager.GetString("TyreOrderDetail_ProdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProdLineDescription.
        /// </summary>
        public static string TyreOrderDetail_ProdLineDescription {
            get {
                return ResourceManager.GetString("TyreOrderDetail_ProdLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProdNo.
        /// </summary>
        public static string TyreOrderDetail_ProdNo {
            get {
                return ResourceManager.GetString("TyreOrderDetail_ProdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedQty.
        /// </summary>
        public static string TyreOrderDetail_ReceivedQty {
            get {
                return ResourceManager.GetString("TyreOrderDetail_ReceivedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string TyreOrderDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("TyreOrderDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefOrderNo.
        /// </summary>
        public static string TyreOrderDetail_RefOrderNo {
            get {
                return ResourceManager.GetString("TyreOrderDetail_RefOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeqGroup.
        /// </summary>
        public static string TyreOrderDetail_SeqGroup {
            get {
                return ResourceManager.GetString("TyreOrderDetail_SeqGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedQty.
        /// </summary>
        public static string TyreOrderDetail_ShippedQty {
            get {
                return ResourceManager.GetString("TyreOrderDetail_ShippedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string TyreOrderDetail_UnitCount {
            get {
                return ResourceManager.GetString("TyreOrderDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string TyreOrderDetail_Uom {
            get {
                return ResourceManager.GetString("TyreOrderDetail_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VanNo.
        /// </summary>
        public static string TyreOrderDetail_VanNo {
            get {
                return ResourceManager.GetString("TyreOrderDetail_VanNo", resourceCulture);
            }
        }
    }
}
