//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateDO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateDO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.CreateDO", typeof(CreateDO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string CreateDO_CreateDate {
            get {
                return ResourceManager.GetString("CreateDO_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUser.
        /// </summary>
        public static string CreateDO_CreateUser {
            get {
                return ResourceManager.GetString("CreateDO_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoLine.
        /// </summary>
        public static string CreateDO_DoLine {
            get {
                return ResourceManager.GetString("CreateDO_DoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoNo.
        /// </summary>
        public static string CreateDO_DoNo {
            get {
                return ResourceManager.GetString("CreateDO_DoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCount.
        /// </summary>
        public static string CreateDO_ErrorCount {
            get {
                return ResourceManager.GetString("CreateDO_ErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessage.
        /// </summary>
        public static string CreateDO_ErrorMessage {
            get {
                return ResourceManager.GetString("CreateDO_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string CreateDO_Item {
            get {
                return ResourceManager.GetString("CreateDO_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string CreateDO_LastModifyDate {
            get {
                return ResourceManager.GetString("CreateDO_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUser.
        /// </summary>
        public static string CreateDO_LastModifyUser {
            get {
                return ResourceManager.GetString("CreateDO_LastModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string CreateDO_LocationFrom {
            get {
                return ResourceManager.GetString("CreateDO_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string CreateDO_LocationTo {
            get {
                return ResourceManager.GetString("CreateDO_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpReference.
        /// </summary>
        public static string CreateDO_OpReference {
            get {
                return ResourceManager.GetString("CreateDO_OpReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string CreateDO_OrderNo {
            get {
                return ResourceManager.GetString("CreateDO_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string CreateDO_Plant {
            get {
                return ResourceManager.GetString("CreateDO_Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string CreateDO_Qty {
            get {
                return ResourceManager.GetString("CreateDO_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPCreateDate.
        /// </summary>
        public static string CreateDO_SAPCreateDate {
            get {
                return ResourceManager.GetString("CreateDO_SAPCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CreateDO_Status {
            get {
                return ResourceManager.GetString("CreateDO_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string CreateDO_Uom {
            get {
                return ResourceManager.GetString("CreateDO_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTime.
        /// </summary>
        public static string CreateDO_WindowTime {
            get {
                return ResourceManager.GetString("CreateDO_WindowTime", resourceCulture);
            }
        }
    }
}
