//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRSL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRSL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.CRSL", typeof(CRSL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string CRSL_CreateDate {
            get {
                return ResourceManager.GetString("CRSL_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateFrom.
        /// </summary>
        public static string CRSL_DateFrom {
            get {
                return ResourceManager.GetString("CRSL_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTo.
        /// </summary>
        public static string CRSL_DateTo {
            get {
                return ResourceManager.GetString("CRSL_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBELN.
        /// </summary>
        public static string CRSL_EBELN {
            get {
                return ResourceManager.GetString("CRSL_EBELN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBELP.
        /// </summary>
        public static string CRSL_EBELP {
            get {
                return ResourceManager.GetString("CRSL_EBELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EINDT.
        /// </summary>
        public static string CRSL_EINDT {
            get {
                return ResourceManager.GetString("CRSL_EINDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCount.
        /// </summary>
        public static string CRSL_ErrorCount {
            get {
                return ResourceManager.GetString("CRSL_ErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETENR.
        /// </summary>
        public static string CRSL_ETENR {
            get {
                return ResourceManager.GetString("CRSL_ETENR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRBNR.
        /// </summary>
        public static string CRSL_FRBNR {
            get {
                return ResourceManager.GetString("CRSL_FRBNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string CRSL_LastModifyDate {
            get {
                return ResourceManager.GetString("CRSL_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFNR.
        /// </summary>
        public static string CRSL_LIFNR {
            get {
                return ResourceManager.GetString("CRSL_LIFNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATNR.
        /// </summary>
        public static string CRSL_MATNR {
            get {
                return ResourceManager.GetString("CRSL_MATNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENGE.
        /// </summary>
        public static string CRSL_MENGE {
            get {
                return ResourceManager.GetString("CRSL_MENGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE.
        /// </summary>
        public static string CRSL_MESSAGE {
            get {
                return ResourceManager.GetString("CRSL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGTXT.
        /// </summary>
        public static string CRSL_SGTXT {
            get {
                return ResourceManager.GetString("CRSL_SGTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CRSL_Status {
            get {
                return ResourceManager.GetString("CRSL_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WERKS.
        /// </summary>
        public static string CRSL_WERKS {
            get {
                return ResourceManager.GetString("CRSL_WERKS", resourceCulture);
            }
        }
    }
}
