//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IpShipInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IpShipInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.IpShipInfo", typeof(IpShipInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASNNR.
        /// </summary>
        public static string IpShipInfo_ASNNR {
            get {
                return ResourceManager.GetString("IpShipInfo_ASNNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string IpShipInfo_CreateDate {
            get {
                return ResourceManager.GetString("IpShipInfo_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateOrCancel.
        /// </summary>
        public static string IpShipInfo_CreateOrCancel {
            get {
                return ResourceManager.GetString("IpShipInfo_CreateOrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string IpShipInfo_CreateUserName {
            get {
                return ResourceManager.GetString("IpShipInfo_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryDate.
        /// </summary>
        public static string IpShipInfo_DeliveryDate {
            get {
                return ResourceManager.GetString("IpShipInfo_DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNSTR.
        /// </summary>
        public static string IpShipInfo_DNSTR {
            get {
                return ResourceManager.GetString("IpShipInfo_DNSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBELN.
        /// </summary>
        public static string IpShipInfo_EBELN {
            get {
                return ResourceManager.GetString("IpShipInfo_EBELN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBELP.
        /// </summary>
        public static string IpShipInfo_EBELP {
            get {
                return ResourceManager.GetString("IpShipInfo_EBELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCount.
        /// </summary>
        public static string IpShipInfo_ErrorCount {
            get {
                return ResourceManager.GetString("IpShipInfo_ErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessage.
        /// </summary>
        public static string IpShipInfo_ErrorMessage {
            get {
                return ResourceManager.GetString("IpShipInfo_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G_LFIMG.
        /// </summary>
        public static string IpShipInfo_G_LFIMG {
            get {
                return ResourceManager.GetString("IpShipInfo_G_LFIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GISTR.
        /// </summary>
        public static string IpShipInfo_GISTR {
            get {
                return ResourceManager.GetString("IpShipInfo_GISTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDelivery.
        /// </summary>
        public static string IpShipInfo_IsDelivery {
            get {
                return ResourceManager.GetString("IpShipInfo_IsDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string IpShipInfo_LastModifyDate {
            get {
                return ResourceManager.GetString("IpShipInfo_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string IpShipInfo_LastModifyUserName {
            get {
                return ResourceManager.GetString("IpShipInfo_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LESID.
        /// </summary>
        public static string IpShipInfo_LESID {
            get {
                return ResourceManager.GetString("IpShipInfo_LESID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGORT.
        /// </summary>
        public static string IpShipInfo_LGORT {
            get {
                return ResourceManager.GetString("IpShipInfo_LGORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATNR.
        /// </summary>
        public static string IpShipInfo_MATNR {
            get {
                return ResourceManager.GetString("IpShipInfo_MATNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBELN_VL.
        /// </summary>
        public static string IpShipInfo_VBELN_VL {
            get {
                return ResourceManager.GetString("IpShipInfo_VBELN_VL", resourceCulture);
            }
        }
    }
}
