//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProdOpBackflush {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProdOpBackflush() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.ProdOpBackflush", typeof(ProdOpBackflush).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUFNR.
        /// </summary>
        public static string ProdOpBackflush_AUFNR {
            get {
                return ResourceManager.GetString("ProdOpBackflush_AUFNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string ProdOpBackflush_CreateDate {
            get {
                return ResourceManager.GetString("ProdOpBackflush_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCount.
        /// </summary>
        public static string ProdOpBackflush_ErrorCount {
            get {
                return ResourceManager.GetString("ProdOpBackflush_ErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMNG.
        /// </summary>
        public static string ProdOpBackflush_GAMNG {
            get {
                return ResourceManager.GetString("ProdOpBackflush_GAMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string ProdOpBackflush_OrderNo {
            get {
                return ResourceManager.GetString("ProdOpBackflush_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProdLine.
        /// </summary>
        public static string ProdOpBackflush_ProdLine {
            get {
                return ResourceManager.GetString("ProdOpBackflush_ProdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRAP.
        /// </summary>
        public static string ProdOpBackflush_SCRAP {
            get {
                return ResourceManager.GetString("ProdOpBackflush_SCRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ProdOpBackflush_Status {
            get {
                return ResourceManager.GetString("ProdOpBackflush_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKCENTER.
        /// </summary>
        public static string ProdOpBackflush_WORKCENTER {
            get {
                return ResourceManager.GetString("ProdOpBackflush_WORKCENTER", resourceCulture);
            }
        }
    }
}
