IF EXISTS(SELECT * FROM SYS.objects WHERE type='V' AND name='VIEW_OrderDet')
	DROP VIEW VIEW_OrderDet
GO

CREATE VIEW VIEW_OrderDet
AS
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_0 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_1 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_2 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_3 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_4 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_5 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_6 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_7 AS a
UNION ALL
SELECT a.Id,a.OrderNo,a.OrderType,a.OrderSubType,a.Seq,a.ExtNo,a.ExtSeq,a.StartDate,a.EndDate,a.ScheduleType,a.Item,a.ItemDesc,a.RefItemCode,a.Uom,a.BaseUom,a.UC,a.UCDesc,a.MinUC,a.Container,a.ContainerDesc,a.QualityType,a.ManufactureParty,a.ReqQty,a.OrderQty,a.ShipQty,a.RecQty,a.RejQty,a.ScrapQty,a.PickQty,a.UnitQty,a.RecLotSize,a.LocFrom,a.LocFromNm,a.LocTo,a.LocToNm,a.IsInspect,a.BillAddr,a.BillAddrDesc,a.PriceList,a.UnitPrice,a.IsProvEst,a.Tax,a.IsIncludeTax,a.Currency,a.Bom,a.Routing,a.BillTerm,a.PickStrategy,a.ExtraDmdSource,a.IsScanHu,a.ReserveNo,a.ReserveLine,a.ZOPWZ,a.ZOPID,a.ZOPDS,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.BinTo,a.WMSSeq,a.IsChangeUC,a.AUFNR,a.ICHARG,a.BWART,a.IsCreatePickList FROM ORD_OrderDet_8 AS a
GO
