IF EXISTS(SELECT * FROM SYS.objects WHERE type='V' AND name='VIEW_RecMstr')
	DROP VIEW VIEW_RecMstr
GO

CREATE VIEW VIEW_RecMstr
AS
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_0 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_1 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_2 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_3 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_4 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_5 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_6 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_7 AS a
UNION ALL
SELECT a.RecNo,a.ExtRecNo,a.IpNo,a.SeqNo,a.Status,a.Type,a.OrderType,a.OrderSubType,a.QualityType,a.PartyFrom,a.PartyFromNm,a.PartyTo,a.PartyToNm,a.ShipFrom,a.ShipFromAddr,a.ShipFromTel,a.ShipFromCell,a.ShipFromFax,a.ShipFromContact,a.ShipTo,a.ShipToAddr,a.ShipToTel,a.ShipToCell,a.ShipToFax,a.ShipToContact,a.Dock,a.EffDate,a.IsPrintRec,a.IsRecPrinted,a.IsCheckPartyFromAuth,a.IsCheckPartyToAuth,a.RecTemplate,a.CreateUser,a.CreateUserNm,a.CreateDate,a.LastModifyUser,a.LastModifyUserNm,a.LastModifyDate,a.Version,a.WMSNo,a.CreateHuOpt,a.IsRecScanHu,a.Flow,a.CancelReason FROM ORD_RecMstr_8 AS a
GO
