//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HuStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HuStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.View.HuStatus", typeof(HuStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string HuStatus_CreateDate {
            get {
                return ResourceManager.GetString("HuStatus_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string HuStatus_CreateUserName {
            get {
                return ResourceManager.GetString("HuStatus_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuId.
        /// </summary>
        public static string HuStatus_HuId {
            get {
                return ResourceManager.GetString("HuStatus_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string HuStatus_Item {
            get {
                return ResourceManager.GetString("HuStatus_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string HuStatus_ItemDescription {
            get {
                return ResourceManager.GetString("HuStatus_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string HuStatus_Location {
            get {
                return ResourceManager.GetString("HuStatus_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string HuStatus_LocationFrom {
            get {
                return ResourceManager.GetString("HuStatus_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string HuStatus_LocationTo {
            get {
                return ResourceManager.GetString("HuStatus_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string HuStatus_LotNo {
            get {
                return ResourceManager.GetString("HuStatus_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureDate.
        /// </summary>
        public static string HuStatus_ManufactureDate {
            get {
                return ResourceManager.GetString("HuStatus_ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string HuStatus_ManufactureParty {
            get {
                return ResourceManager.GetString("HuStatus_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string HuStatus_Qty {
            get {
                return ResourceManager.GetString("HuStatus_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string HuStatus_ReferenceItemCode {
            get {
                return ResourceManager.GetString("HuStatus_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string HuStatus_UnitCount {
            get {
                return ResourceManager.GetString("HuStatus_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string HuStatus_Uom {
            get {
                return ResourceManager.GetString("HuStatus_Uom", resourceCulture);
            }
        }
    }
}
