//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KanBanCalcResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KanBanCalcResult() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.View.KanBanCalcResult", typeof(KanBanCalcResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode.
        /// </summary>
        public static string KanBanCalcResult_BarCode {
            get {
                return ResourceManager.GetString("KanBanCalcResult_BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchNo.
        /// </summary>
        public static string KanBanCalcResult_BatchNo {
            get {
                return ResourceManager.GetString("KanBanCalcResult_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BianHao.
        /// </summary>
        public static string KanBanCalcResult_BianHao {
            get {
                return ResourceManager.GetString("KanBanCalcResult_BianHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcResult.
        /// </summary>
        public static string KanBanCalcResult_CalcResult {
            get {
                return ResourceManager.GetString("KanBanCalcResult_CalcResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeType.
        /// </summary>
        public static string KanBanCalcResult_CodeType {
            get {
                return ResourceManager.GetString("KanBanCalcResult_CodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffFreDate.
        /// </summary>
        public static string KanBanCalcResult_EffFreDate {
            get {
                return ResourceManager.GetString("KanBanCalcResult_EffFreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowDetId.
        /// </summary>
        public static string KanBanCalcResult_FlowDetId {
            get {
                return ResourceManager.GetString("KanBanCalcResult_FlowDetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreezeNo.
        /// </summary>
        public static string KanBanCalcResult_FreezeNo {
            get {
                return ResourceManager.GetString("KanBanCalcResult_FreezeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string KanBanCalcResult_Item {
            get {
                return ResourceManager.GetString("KanBanCalcResult_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDesc.
        /// </summary>
        public static string KanBanCalcResult_ItemDesc {
            get {
                return ResourceManager.GetString("KanBanCalcResult_ItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KanbanDeltaNum.
        /// </summary>
        public static string KanBanCalcResult_KanbanDeltaNum {
            get {
                return ResourceManager.GetString("KanBanCalcResult_KanbanDeltaNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KanbanNum.
        /// </summary>
        public static string KanBanCalcResult_KanbanNum {
            get {
                return ResourceManager.GetString("KanBanCalcResult_KanbanNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCCode.
        /// </summary>
        public static string KanBanCalcResult_LCCode {
            get {
                return ResourceManager.GetString("KanBanCalcResult_LCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadTime.
        /// </summary>
        public static string KanBanCalcResult_LeadTime {
            get {
                return ResourceManager.GetString("KanBanCalcResult_LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocBin.
        /// </summary>
        public static string KanBanCalcResult_LocBin {
            get {
                return ResourceManager.GetString("KanBanCalcResult_LocBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string KanBanCalcResult_LocTo {
            get {
                return ResourceManager.GetString("KanBanCalcResult_LocTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string KanBanCalcResult_Lot {
            get {
                return ResourceManager.GetString("KanBanCalcResult_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxQty.
        /// </summary>
        public static string KanBanCalcResult_MaxQty {
            get {
                return ResourceManager.GetString("KanBanCalcResult_MaxQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewNo.
        /// </summary>
        public static string KanBanCalcResult_NewNo {
            get {
                return ResourceManager.GetString("KanBanCalcResult_NewNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpRef.
        /// </summary>
        public static string KanBanCalcResult_OpRef {
            get {
                return ResourceManager.GetString("KanBanCalcResult_OpRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo.
        /// </summary>
        public static string KanBanCalcResult_PartyTo {
            get {
                return ResourceManager.GetString("KanBanCalcResult_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QiTiaoBian.
        /// </summary>
        public static string KanBanCalcResult_QiTiaoBian {
            get {
                return ResourceManager.GetString("KanBanCalcResult_QiTiaoBian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string KanBanCalcResult_Qty {
            get {
                return ResourceManager.GetString("KanBanCalcResult_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafeTime.
        /// </summary>
        public static string KanBanCalcResult_SafeTime {
            get {
                return ResourceManager.GetString("KanBanCalcResult_SafeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        public static string KanBanCalcResult_Shelf {
            get {
                return ResourceManager.GetString("KanBanCalcResult_Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string KanBanCalcResult_Supplier {
            get {
                return ResourceManager.GetString("KanBanCalcResult_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierName.
        /// </summary>
        public static string KanBanCalcResult_SupplierName {
            get {
                return ResourceManager.GetString("KanBanCalcResult_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TravelTimes.
        /// </summary>
        public static string KanBanCalcResult_TravelTimes {
            get {
                return ResourceManager.GetString("KanBanCalcResult_TravelTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string KanBanCalcResult_Type {
            get {
                return ResourceManager.GetString("KanBanCalcResult_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Count Desc.
        /// </summary>
        public static string KanBanCalcResult_UCDesc {
            get {
                return ResourceManager.GetString("KanBanCalcResult_UCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Count.
        /// </summary>
        public static string KanBanCalcResult_UnitCount {
            get {
                return ResourceManager.GetString("KanBanCalcResult_UnitCount", resourceCulture);
            }
        }
    }
}
