//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationDetailView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationDetailView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.View.LocationDetailView", typeof(LocationDetailView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATPQty.
        /// </summary>
        public static string LocationDetailView_ATPQty {
            get {
                return ResourceManager.GetString("LocationDetailView_ATPQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsignmentQty.
        /// </summary>
        public static string LocationDetailView_ConsignmentQty {
            get {
                return ResourceManager.GetString("LocationDetailView_ConsignmentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CsQty.
        /// </summary>
        public static string LocationDetailView_CsQty {
            get {
                return ResourceManager.GetString("LocationDetailView_CsQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LocationDetailView_Description {
            get {
                return ResourceManager.GetString("LocationDetailView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreezeQty.
        /// </summary>
        public static string LocationDetailView_FreezeQty {
            get {
                return ResourceManager.GetString("LocationDetailView_FreezeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectQty.
        /// </summary>
        public static string LocationDetailView_InspectQty {
            get {
                return ResourceManager.GetString("LocationDetailView_InspectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCS.
        /// </summary>
        public static string LocationDetailView_IsCS {
            get {
                return ResourceManager.GetString("LocationDetailView_IsCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string LocationDetailView_Item {
            get {
                return ResourceManager.GetString("LocationDetailView_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationDetailView_Location {
            get {
                return ResourceManager.GetString("LocationDetailView_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string LocationDetailView_LotNo {
            get {
                return ResourceManager.GetString("LocationDetailView_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string LocationDetailView_ManufactureParty {
            get {
                return ResourceManager.GetString("LocationDetailView_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LocationDetailView_Name {
            get {
                return ResourceManager.GetString("LocationDetailView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant.
        /// </summary>
        public static string LocationDetailView_plant {
            get {
                return ResourceManager.GetString("LocationDetailView_plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string LocationDetailView_Qty {
            get {
                return ResourceManager.GetString("LocationDetailView_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualifyQty.
        /// </summary>
        public static string LocationDetailView_QualifyQty {
            get {
                return ResourceManager.GetString("LocationDetailView_QualifyQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityType.
        /// </summary>
        public static string LocationDetailView_QualityType {
            get {
                return ResourceManager.GetString("LocationDetailView_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefItemCode.
        /// </summary>
        public static string LocationDetailView_RefItemCode {
            get {
                return ResourceManager.GetString("LocationDetailView_RefItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefNo.
        /// </summary>
        public static string LocationDetailView_RefNo {
            get {
                return ResourceManager.GetString("LocationDetailView_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region.
        /// </summary>
        public static string LocationDetailView_region {
            get {
                return ResourceManager.GetString("LocationDetailView_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RejectQty.
        /// </summary>
        public static string LocationDetailView_RejectQty {
            get {
                return ResourceManager.GetString("LocationDetailView_RejectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPLocation.
        /// </summary>
        public static string LocationDetailView_SAPLocation {
            get {
                return ResourceManager.GetString("LocationDetailView_SAPLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suppliers.
        /// </summary>
        public static string LocationDetailView_suppliers {
            get {
                return ResourceManager.GetString("LocationDetailView_suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string LocationDetailView_Uom {
            get {
                return ResourceManager.GetString("LocationDetailView_Uom", resourceCulture);
            }
        }
    }
}
