//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InspectMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InspectMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INP.InspectMaster", typeof(InspectMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectMaster Added.
        /// </summary>
        public static string InspectMaster_Added {
            get {
                return ResourceManager.GetString("InspectMaster_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string InspectMaster_CreateDate {
            get {
                return ResourceManager.GetString("InspectMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string InspectMaster_CreateUserName {
            get {
                return ResourceManager.GetString("InspectMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string InspectMaster_EndDate {
            get {
                return ResourceManager.GetString("InspectMaster_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectNo.
        /// </summary>
        public static string InspectMaster_InspectNo {
            get {
                return ResourceManager.GetString("InspectMaster_InspectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpNo.
        /// </summary>
        public static string InspectMaster_IpNo {
            get {
                return ResourceManager.GetString("InspectMaster_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsATP.
        /// </summary>
        public static string InspectMaster_IsATP {
            get {
                return ResourceManager.GetString("InspectMaster_IsATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrint.
        /// </summary>
        public static string InspectMaster_IsPrint {
            get {
                return ResourceManager.GetString("InspectMaster_IsPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string InspectMaster_LocationFrom {
            get {
                return ResourceManager.GetString("InspectMaster_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptNo.
        /// </summary>
        public static string InspectMaster_ReceiptNo {
            get {
                return ResourceManager.GetString("InspectMaster_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceNo.
        /// </summary>
        public static string InspectMaster_ReferenceNo {
            get {
                return ResourceManager.GetString("InspectMaster_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string InspectMaster_Region {
            get {
                return ResourceManager.GetString("InspectMaster_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string InspectMaster_StartDate {
            get {
                return ResourceManager.GetString("InspectMaster_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string InspectMaster_Status {
            get {
                return ResourceManager.GetString("InspectMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect Detail.
        /// </summary>
        public static string InspectMaster_Tab_InspectDetail {
            get {
                return ResourceManager.GetString("InspectMaster_Tab_InspectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect Result.
        /// </summary>
        public static string InspectMaster_Tab_InspectResult {
            get {
                return ResourceManager.GetString("InspectMaster_Tab_InspectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectMaster.
        /// </summary>
        public static string InspectMaster_Title_View {
            get {
                return ResourceManager.GetString("InspectMaster_Title_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectMaster_Transfered.
        /// </summary>
        public static string InspectMaster_Transfered {
            get {
                return ResourceManager.GetString("InspectMaster_Transfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string InspectMaster_Type {
            get {
                return ResourceManager.GetString("InspectMaster_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMSNo.
        /// </summary>
        public static string InspectMaster_WMSNo {
            get {
                return ResourceManager.GetString("InspectMaster_WMSNo", resourceCulture);
            }
        }
    }
}
