IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ORD_SAPOrderOp]') AND type in (N'U'))
DROP TABLE [dbo].[ORD_SAPOrderOp]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORD_SAPOrderOp](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[OrderNo] [varchar](50) NULL,
	[WorkCenter] [varchar](50) NULL,
	[AUFNR] [varchar](50) NULL,
	[AUFPL] [int] NULL,
	[PLNFL] [varchar](50) NULL,
	[VORNR] [varchar](50) NULL,
 CONSTRAINT [PK_ORD_OrderRoutingDet] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ORD_SAPOrderOp] ADD  DEFAULT (getdate()) FOR [CreateDate]
GO


