IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CUST_ManualGenOrderIgnoreWorkCenter]') AND type in (N'U'))
DROP TABLE [dbo].[CUST_ManualGenOrderIgnoreWorkCenter]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CUST_ManualGenOrderIgnoreWorkCenter](
	[WorkCenter] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CUST_ManualGenOrderIgnoreWorkCenter] PRIMARY KEY CLUSTERED 
(
	[WorkCenter] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


