delete from CUST_DeferredFeedCounter
delete from CUST_CabOut
delete from CUST_OpReport
delete from INV_LocTransDet
delete from INV_LocTransDet_0
delete from INV_LocTransDet_1
delete from INV_LocTransDet_2
delete from INV_LocTransDet_3
delete from INV_LocTransDet_4
delete from INV_LocTransDet_5
delete from INV_LocTransDet_6
delete from INV_LocTransDet_7
delete from INV_LocTransDet_8
delete from INV_LocTransDet_9
delete from INV_LocTransDet_10
delete from INV_LocTransDet_11
delete from INV_LocTransDet_12
delete from INV_LocTransDet_13
delete from INV_LocTransDet_14
delete from INV_LocTransDet_15
delete from INV_LocTransDet_16
delete from INV_LocTransDet_17
delete from INV_LocTransDet_18
delete from INV_LocTransDet_19
delete from INV_LocTrans
delete from INV_LocTrans_0
delete from INV_LocTrans_1
delete from INV_LocTrans_2
delete from INV_LocTrans_3
delete from INV_LocTrans_4
delete from INV_LocTrans_5
delete from INV_LocTrans_6
delete from INV_LocTrans_7
delete from INV_LocTrans_8
delete from INV_LocTrans_9
delete from INV_LocTrans_10
delete from INV_LocTrans_11
delete from INV_LocTrans_12
delete from INV_LocTrans_13
delete from INV_LocTrans_14
delete from INV_LocTrans_15
delete from INV_LocTrans_16
delete from INV_LocTrans_17
delete from INV_LocTrans_18
delete from INV_LocTrans_19
delete from INV_LocationLotDet
delete from INV_LocationLotDet_0
delete from INV_LocationLotDet_1
delete from INV_LocationLotDet_2
delete from INV_LocationLotDet_3
delete from INV_LocationLotDet_4
delete from INV_LocationLotDet_5
delete from INV_LocationLotDet_6
delete from INV_LocationLotDet_7
delete from INV_LocationLotDet_8
delete from INV_LocationLotDet_9
delete from INV_LocationLotDet_10
delete from INV_LocationLotDet_11
delete from INV_LocationLotDet_12
delete from INV_LocationLotDet_13
delete from INV_LocationLotDet_14
delete from INV_LocationLotDet_15
delete from INV_LocationLotDet_16
delete from INV_LocationLotDet_17
delete from INV_LocationLotDet_18
delete from INV_LocationLotDet_19
delete from INV_StockTakeResult
delete from INV_StockTakeDet
delete from INV_StockTakeItem
delete from INV_StockTakeLoc
delete from INV_StockTakeMstr
delete from INP_ConcessionDet
delete from INP_ConcessionMstr
delete from INP_RejectDet
delete from INP_RejectMstr
delete from INP_InspectResult
delete from INP_InspectDet
delete from INP_InspectMstr
delete from ORD_OrderBackflushDet
delete from ORD_OrderBindingDet
delete from ORD_OrderBinding
delete from ORD_OrderBomDet
delete from ORD_OrderOp
delete from ORD_OrderBomCPTime
delete from ORD_RecLocationDet
delete from ORD_RecLocationDet_0
delete from ORD_RecLocationDet_1
delete from ORD_RecLocationDet_2
delete from ORD_RecLocationDet_3
delete from ORD_RecLocationDet_4
delete from ORD_RecLocationDet_5
delete from ORD_RecLocationDet_6
delete from ORD_RecLocationDet_7
delete from ORD_RecLocationDet_8
delete from PRD_PlanBackflush
delete from ORD_RecDet
delete from ORD_RecDet_0
delete from ORD_RecDet_1
delete from ORD_RecDet_2
delete from ORD_RecDet_3
delete from ORD_RecDet_4
delete from ORD_RecDet_5
delete from ORD_RecDet_6
delete from ORD_RecDet_7
delete from ORD_RecDet_8
delete from ORD_RecMstr
delete from ORD_RecMstr_0
delete from ORD_RecMstr_1
delete from ORD_RecMstr_2
delete from ORD_RecMstr_3
delete from ORD_RecMstr_4
delete from ORD_RecMstr_5
delete from ORD_RecMstr_6
delete from ORD_RecMstr_7
delete from ORD_RecMstr_8
delete from BIL_BillTrans
delete from BIL_ActBill
delete from BIL_PlanBill
delete from ORD_IpLocationDet
delete from ORD_IpLocationDet_0
delete from ORD_IpLocationDet_1
delete from ORD_IpLocationDet_2
delete from ORD_IpLocationDet_3
delete from ORD_IpLocationDet_4
delete from ORD_IpLocationDet_5
delete from ORD_IpLocationDet_6
delete from ORD_IpLocationDet_7
delete from ORD_IpLocationDet_8
delete from ORD_IpDet
delete from ORD_IpDet_0
delete from ORD_IpDet_1
delete from ORD_IpDet_2
delete from ORD_IpDet_3
delete from ORD_IpDet_4
delete from ORD_IpDet_5
delete from ORD_IpDet_6
delete from ORD_IpDet_7
delete from ORD_IpDet_8
delete from ORD_IpMstr
delete from ORD_IpMstr_0
delete from ORD_IpMstr_1
delete from ORD_IpMstr_2
delete from ORD_IpMstr_3
delete from ORD_IpMstr_4
delete from ORD_IpMstr_5
delete from ORD_IpMstr_6
delete from ORD_IpMstr_7
delete from ORD_IpMstr_8
delete from ORD_OrderItemTrace
delete from ORD_OrderItemTraceResult
delete from ORD_PickListResult
delete from ORD_PickListDet
delete from ORD_PickListMstr
delete from ORD_PickHu
delete from ORD_PickResult
delete from ORD_PickTask
delete from ORD_SeqDet
delete from ORD_SeqMstr
delete from ORD_OrderDet
delete from ORD_OrderDet_0
delete from ORD_OrderDet_1
delete from ORD_OrderDet_2
delete from ORD_OrderDet_3
delete from ORD_OrderDet_4
delete from ORD_OrderDet_5
delete from ORD_OrderDet_6
delete from ORD_OrderDet_7
delete from ORD_OrderDet_8
delete from ORD_OrderMstr
delete from ORD_OrderMstr_0
delete from ORD_OrderMstr_1
delete from ORD_OrderMstr_2
delete from ORD_OrderMstr_3
delete from ORD_OrderMstr_4
delete from ORD_OrderMstr_5
delete from ORD_OrderMstr_6
delete from ORD_OrderMstr_7
delete from ORD_OrderMstr_8
delete from ORD_OrderOpCPTime
delete from ORD_OrderOpReport
delete from ORD_OrderSeq
delete from ORD_MiscOrderLocationDet
delete from ORD_MiscOrderDet
delete from ORD_MiscOrderMstr
delete from ORD_OrderTracer
delete from PRD_ProdLineLocationDet
delete from INV_Hu
delete from SYS_NumCtrl
delete from CUST_ScheduleLineItem
delete from SAP_ProdBomDet
delete from SAP_ProdOpReport
delete from SAP_ProdRoutingDet
delete from SAP_CancelProdOpReport
delete from SAP_ProdOrder
delete from SCM_OpRefBalance
truncate table LOG_GenJITOrder
truncate table LOG_GenKBOrder
truncate table LOG_GenOrder4VanProdLine
truncate table LOG_GenProductOrder
truncate table LOG_GenSequenceOrder
truncate table LOG_GenVanProdOrder
truncate table LOG_OrderTrace
truncate table LOG_OrderTraceDet
truncate table LOG_RunLeanEngine
truncate table LOG_SnapshotFlowDet4LeanEngine
truncate table LOG_VanOrderTrace
truncate table LOG_VanOrderBomTrace
update SCM_FlowStrategy  set PreWinTime = NULL 
update scm_seqgroup set PrevOrderNo = null,prevseq = null,prevsubseq = null,prevtracecode = null,prevdeliverydate = null,prevdeliverycount = null